Repository VenusProtocol/venus-protocol-interface, pull requests merged in 2022-08, with the labels that each got.

#787 Prevent wallet logo from expending in auth modal
  src/components/AuthModal/AccountDetails/styles.ts
Labels: 1.1.1

#781 [VEN-358] Force LUNA and UST disabling as collateral
  src/clients/api/__mocks__/index.ts
  src/components/Layout/Banner/index.tsx
  src/components/Layout/Banner/styles.ts
  src/components/Layout/ClaimXvsRewardButton/index.tsx
  src/components/Layout/index.tsx
  src/components/LunaUstWarningModal/index.tsx
  src/components/LunaUstWarningModal/styles.ts
  src/components/index.ts
  src/context/DisableLunaUstWarning/index.test.tsx
  src/context/DisableLunaUstWarning/index.tsx
  src/context/SuccessfulTransactionModalContext.tsx
  src/pages/App.tsx
  src/pages/ConvertVrt/Convert/index.tsx
  src/pages/ConvertVrt/Withdraw/index.tsx
  src/pages/Dashboard/Markets/BorrowMarket/index.stories.tsx
  src/pages/Dashboard/Markets/BorrowMarket/index.tsx
  src/pages/Dashboard/Markets/SupplyMarket/index.stories.tsx
  src/pages/Dashboard/Markets/SupplyMarket/index.tsx
  src/pages/Dashboard/MintRepayVai/RepayVai/index.tsx
  src/pages/Dashboard/Modals/LunaUstWarning/index.tsx
  src/pages/Dashboard/Modals/LunaUstWarning/styles.ts
  src/pages/Dashboard/Modals/index.ts
  src/pages/Dashboard/index.spec.tsx
  src/pages/Dashboard/index.tsx
  src/pages/Dashboard/useLunaUstWarningModal.ts
  src/pages/Vault/VaultItem/index.tsx
  src/testUtils/renderComponent.tsx
  src/translation/translations/en.json
Labels: 1.1.1

#801 Bump package version to 1.1.2
  package.json
Labels: 1.1.2

#802 Release v1.1.2
  package.json
  src/__mocks__/api/proposals.json
  src/assets/img/wallets/bitKeepLogo.svg
  src/clients/api/queries/getProposals/__snapshots__/getProposal.spec.ts.snap
  src/clients/api/queries/getProposals/__snapshots__/index.spec.ts.snap
  src/clients/api/queries/getProposals/getProposal.spec.ts
  src/clients/api/queries/getProposals/getProposal.ts
  src/clients/api/queries/getProposals/index.spec.ts
  src/clients/api/queries/getProposals/index.ts
  src/clients/api/queries/getProposals/types.ts
  src/clients/web3/addTokenToWallet.ts
  src/clients/web3/connectors.ts
  src/clients/web3/types.ts
  src/clients/web3/walletDetectionUtils.ts
  src/components/AuthModal/constants.ts
  src/components/Layout/Header/Title/index.tsx
  src/components/Layout/Header/Title/styles.ts
  src/components/ReadableActionSignature/formatSignature.ts
  src/components/ReadableActionSignature/index.tsx
  src/pages/App.tsx
  src/pages/MarketDetails/__snapshots__/index.spec.tsx.snap
  src/pages/MarketDetails/index.stories.tsx
  src/pages/MarketDetails/index.tsx
  src/pages/MarketDetails/useGetMarketData.ts
  src/pages/Proposal/Description/index.stories.tsx
  src/pages/Proposal/Description/index.tsx
  src/pages/Vote/CreateProposalModal/ActionAccordion/CallDataFields.tsx
  src/pages/Vote/CreateProposalModal/ActionAccordion/index.tsx
  src/pages/Vote/CreateProposalModal/formatProposalPayload.ts
  src/pages/Vote/CreateProposalModal/index.spec.tsx
  src/pages/Vote/CreateProposalModal/index.tsx
  src/pages/Vote/CreateProposalModal/proposalSchema.ts
  src/pages/Vote/index.spec.tsx
  src/stories/decorators.tsx
  src/testUtils/renderComponent.tsx
  src/translation/translations/en.json
  src/types/index.ts
  src/utilities/formatToProposal.ts
  src/utilities/time.ts
Labels: 1.1.2

#800 [VEN-494] Clean up dashboard in preparation for isolated lending
  src/pages/Dashboard/Markets/BorrowMarket/BorrowingTable.tsx
  src/pages/Dashboard/Markets/BorrowMarket/index.spec.tsx
  src/pages/Dashboard/Markets/BorrowMarket/index.stories.tsx
  src/pages/Dashboard/Markets/BorrowMarket/index.tsx
  src/pages/Dashboard/Markets/SupplyMarket/SuppliedTable.tsx
  src/pages/Dashboard/Markets/SupplyMarket/index.spec.tsx
  src/pages/Dashboard/Markets/SupplyMarket/index.stories.tsx
  src/pages/Dashboard/Markets/SupplyMarket/index.tsx
  src/pages/Dashboard/Markets/index.tsx
  src/pages/Dashboard/MintRepayVai/MintVai/getReadableFeeVai.ts
  src/pages/Dashboard/MintRepayVai/MintVai/index.spec.tsx
  src/pages/Dashboard/MintRepayVai/MintVai/index.tsx
  src/pages/Dashboard/MintRepayVai/RepayVai/index.spec.tsx
  src/pages/Dashboard/MintRepayVai/RepayVai/index.tsx
  src/pages/Dashboard/MintRepayVai/constants.ts
  src/pages/Dashboard/MintRepayVai/index.spec.tsx
  src/pages/Dashboard/MintRepayVai/index.stories.tsx
  src/pages/Dashboard/MintRepayVai/index.tsx
  src/pages/Dashboard/MintRepayVai/styles.ts
  src/pages/Dashboard/MyAccount/MyAccountUi.tsx
  src/pages/Dashboard/MyAccount/index.stories.tsx
  src/pages/Dashboard/MyAccount/index.tsx
  src/pages/Dashboard/MyAccount/styles.ts
  src/pages/Dashboard/index.spec.tsx
  src/pages/Dashboard/index.tsx
Labels: 1.2.0

#804 Fix typo on Market Details page
  src/pages/MarketDetails/__snapshots__/index.spec.tsx.snap
  src/translation/translations/en.json
Labels: hotfix

#803 [VEN-494] Add higher risk tokens notice on Dashboard
  src/components/Icon/icons/gauge.tsx
  src/components/Icon/icons/index.ts
  src/constants/localStorageKeys.ts
  src/pages/Dashboard/HigherRiskTokensNotice/index.tsx
  src/pages/Dashboard/HigherRiskTokensNotice/styles.ts
  src/pages/Dashboard/Markets/BorrowMarket/BorrowingTable.tsx
  src/pages/Dashboard/Markets/BorrowMarket/index.spec.tsx
  src/pages/Dashboard/Markets/BorrowMarket/index.stories.tsx
  src/pages/Dashboard/Markets/BorrowMarket/index.tsx
  src/pages/Dashboard/Markets/SupplyMarket/SuppliedTable.tsx
  src/pages/Dashboard/Markets/SupplyMarket/index.spec.tsx
  src/pages/Dashboard/Markets/SupplyMarket/index.stories.tsx
  src/pages/Dashboard/Markets/SupplyMarket/index.tsx
  src/pages/Dashboard/Markets/index.tsx
  src/pages/Dashboard/Markets/styles.ts
  src/pages/Dashboard/MintRepayVai/MintVai/getReadableFeeVai.ts
  src/pages/Dashboard/MintRepayVai/MintVai/index.spec.tsx
  src/pages/Dashboard/MintRepayVai/MintVai/index.tsx
  src/pages/Dashboard/MintRepayVai/RepayVai/index.spec.tsx
  src/pages/Dashboard/MintRepayVai/RepayVai/index.tsx
  src/pages/Dashboard/MintRepayVai/constants.ts
  src/pages/Dashboard/MintRepayVai/index.spec.tsx
  src/pages/Dashboard/MintRepayVai/index.stories.tsx
  src/pages/Dashboard/MintRepayVai/index.tsx
  src/pages/Dashboard/MintRepayVai/styles.ts
  src/pages/Dashboard/MyAccount/MyAccountUi.tsx
  src/pages/Dashboard/MyAccount/index.stories.tsx
  src/pages/Dashboard/MyAccount/index.tsx
  src/pages/Dashboard/MyAccount/styles.ts
  src/pages/Dashboard/index.spec.tsx
  src/pages/Dashboard/index.tsx
  src/pages/Dashboard/styles.ts
  src/translation/translations/en.json
Labels: 1.2.0

#806 Revert to browser router
  src/pages/App.tsx
  src/pages/Vote/index.spec.tsx
  src/stories/decorators.tsx
  src/testUtils/renderComponent.tsx
Labels: hotfix

#808 [VEN-494] Update dashboard UI
  src/components/ButtonGroup/index.stories.tsx
  src/components/ButtonGroup/index.tsx
  src/components/ButtonGroup/styles.tsx
  src/components/Icon/icons/index.ts
  src/components/Icon/icons/magnifier.tsx
  src/components/Select/index.tsx
  src/components/Select/styles.ts
  src/components/Tabs/index.stories.tsx
  src/components/Tabs/index.tsx
  src/components/Tabs/styles.tsx
  src/components/TextField/index.stories.tsx
  src/components/TextField/index.tsx
  src/components/TextField/styles.ts
  src/components/Toggle/index.stories.tsx
  src/components/Toggle/index.tsx
  src/components/Toggle/styles.ts
  src/components/index.ts
  src/hooks/responsive.ts
  src/pages/Dashboard/Markets/BorrowMarket/BorrowMarketTable.tsx
  src/pages/Dashboard/Markets/BorrowMarket/index.spec.tsx
  src/pages/Dashboard/Markets/BorrowMarket/index.stories.tsx
  src/pages/Dashboard/Markets/BorrowMarket/index.tsx
  src/pages/Dashboard/Markets/Modals/BorrowRepay/AccountData/index.tsx
  src/pages/Dashboard/Markets/Modals/BorrowRepay/Borrow/index.spec.tsx
  src/pages/Dashboard/Markets/Modals/BorrowRepay/Borrow/index.tsx
  src/pages/Dashboard/Markets/Modals/BorrowRepay/Borrow/testIds.ts
  src/pages/Dashboard/Markets/Modals/BorrowRepay/Repay/index.spec.tsx
  src/pages/Dashboard/Markets/Modals/BorrowRepay/Repay/index.tsx
  src/pages/Dashboard/Markets/Modals/BorrowRepay/Repay/styles.ts
  src/pages/Dashboard/Markets/Modals/BorrowRepay/Repay/testIds.ts
  src/pages/Dashboard/Markets/Modals/BorrowRepay/index.spec.tsx
  src/pages/Dashboard/Markets/Modals/BorrowRepay/index.stories.tsx
  src/pages/Dashboard/Markets/Modals/BorrowRepay/index.tsx
  src/pages/Dashboard/Markets/Modals/SupplyWithdraw/SupplyWithdrawForm.tsx
  src/pages/Dashboard/Markets/Modals/SupplyWithdraw/index.spec.tsx
  src/pages/Dashboard/Markets/Modals/SupplyWithdraw/index.stories.tsx
  src/pages/Dashboard/Markets/Modals/SupplyWithdraw/index.tsx
  src/pages/Dashboard/Markets/Modals/index.ts
  src/pages/Dashboard/Markets/Modals/styles.ts
  src/pages/Dashboard/Markets/SupplyMarket/SupplyMarketTable.tsx
  src/pages/Dashboard/Markets/SupplyMarket/index.spec.tsx
  src/pages/Dashboard/Markets/SupplyMarket/index.stories.tsx
  src/pages/Dashboard/Markets/SupplyMarket/index.tsx
  src/pages/Dashboard/Markets/SupplyMarket/styles.ts
  src/pages/Dashboard/Markets/index.tsx
  src/pages/Dashboard/Markets/styles.ts
  src/pages/Dashboard/index.tsx
  src/pages/Dashboard/styles.ts
  src/translation/translations/en.json
  src/types/index.ts
Labels: 1.2.0

#811 [VEN-496] Add TokenGroup component
  src/components/Token/index.stories.tsx
  src/components/Token/index.tsx
  src/components/TokenGroup/index.stories.tsx
  src/components/TokenGroup/index.tsx
  src/components/TokenGroup/styles.ts
Labels: 1.2.0

#812 Improve Select and Toggle components
  src/components/Select/index.stories.tsx
  src/components/Select/index.tsx
  src/components/Select/styles.ts
  src/components/Toggle/index.stories.tsx
  src/components/Toggle/index.tsx
  src/components/Toggle/styles.ts
  src/pages/Dashboard/index.tsx
  src/pages/Dashboard/styles.ts
  src/pages/History/Filters/index.tsx
  src/pages/History/index.tsx
Labels: 1.2.0

#815 [VEN-495][VEN-496] Update Markets page UI
  src/components/CellGroup/index.tsx
  src/components/RiskLevel/index.tsx
  src/components/RiskLevel/styles.ts
  src/components/Select/index.tsx
  src/components/Table/TableCards.tsx
  src/components/Table/styles.ts
  src/components/TokenGroup/index.tsx
  src/components/index.ts
  src/hooks/responsive.ts
  src/pages/App.tsx
  src/pages/Dashboard/Markets/BorrowMarket/BorrowMarketTable.tsx
  src/pages/Dashboard/Markets/SupplyMarket/SupplyMarketTable.tsx
  src/pages/Dashboard/index.tsx
  src/pages/Market/MarketTable/index.tsx
  src/pages/Market/styles.ts
  src/pages/Markets/Header/index.stories.tsx
  src/pages/Markets/Header/index.tsx
  src/pages/Markets/Header/styles.ts
  src/pages/Markets/MarketTable/index.spec.tsx
  src/pages/Markets/MarketTable/index.stories.tsx
  src/pages/Markets/MarketTable/index.tsx
  src/pages/Markets/MarketTable/styles.ts
  src/pages/Markets/index.spec.tsx
  src/pages/Markets/index.tsx
  src/translation/translations/en.json
Labels: 1.2.0
