Repository VenusProtocol/venus-protocol-interface, pull requests merged in 2022-05, with the labels that each got.

#388 Feature: add mobile view for tables
  src/components/v2/Table/index.stories.tsx
  src/components/v2/Table/index.tsx
  src/components/v2/Table/styles.ts
  src/pages/Dashboard/Markets/BorrowMarket/BorrowMarketTable.tsx
  src/pages/Dashboard/Markets/BorrowMarket/BorrowingTable.tsx
  src/pages/Dashboard/Markets/BorrowMarket/index.tsx
  src/pages/Dashboard/Markets/BorrowMarket/styles.ts
  src/pages/Dashboard/Markets/SupplyMarket/SuppliedTable.tsx
  src/pages/Dashboard/Markets/SupplyMarket/SupplyMarketTable.tsx
  src/pages/Dashboard/Markets/SupplyMarket/index.tsx
  src/pages/Dashboard/Markets/SupplyMarket/styles.ts
  src/pages/Dashboard/Markets/index.tsx
  src/pages/Dashboard/Markets/styles.ts
  src/pages/Dashboard/index.spec.tsx
  src/pages/Dashboard/index.tsx
  src/pages/Dashboard/styles.ts
Labels: enhancement

#402 Feature: add notice component
  src/components/index.ts
  src/components/v2/Icon/icons/checkInline.svg
  src/components/v2/Icon/icons/index.tsx
  src/components/v2/Icon/icons/notice.svg
  src/components/v2/Notice/index.stories.tsx
  src/components/v2/Notice/index.tsx
  src/components/v2/Notice/styles.ts
  src/components/v2/Notice/types.ts
Labels: enhancement

#423 Chore: use notice component for Prompt message
  src/components/v2/ConnectWallet/index.tsx
  src/components/v2/ConnectWallet/styles.ts
Labels: enhancement

#436 Update supply form tests
  src/clients/api/index.ts
  src/clients/api/mutations/convertVrt.spec.ts
  src/clients/api/mutations/convertVrt.ts
  src/clients/api/mutations/redeem.spec.ts
  src/clients/api/mutations/redeem.ts
  src/clients/api/mutations/redeemUnderlying.spec.ts
  src/clients/api/mutations/redeemUnderlying.ts
  src/clients/api/mutations/supplyBnb.spec.ts
  src/clients/api/mutations/supplyBnb.ts
  src/clients/api/mutations/supplyNonBnb.spec.ts
  src/clients/api/mutations/supplyNonBnb.ts
  src/clients/api/mutations/useRedeem.ts
  src/clients/api/mutations/useRedeemUnderlying.ts
  src/pages/Dashboard/Modals/SupplyWithdraw/index.spec.tsx
  src/pages/Dashboard/Modals/SupplyWithdraw/index.tsx
Labels: 0.4.0

#451 If user meets threshold they can cancel a proposal
  src/containers/Main/VoteOverview.tsx
Labels: 0.4.0

#449 Update supply balance formatting on supply form
  src/pages/Dashboard/Modals/SupplyWithdraw/SupplyWithdrawForm.tsx
  src/translation/translations/en.json
Labels: 0.4.0

#450 Fix sorting borrowed assets by limit percentage
  src/pages/Dashboard/Markets/BorrowMarket/BorrowingTable.tsx
Labels: 0.4.0

#446 Fix how VAI enabling is determined
  src/context/VaiContext.tsx
Labels: 0.4.0

#448 Use correct token ref to determine decimals on borrow form
  src/pages/Dashboard/Modals/BorrowRepay/Borrow/index.tsx
Labels: 0.4.0

#445 Update two translations
  src/translation/translations/en.json
Labels: 0.4.0

#452 Improve dashboard tables responsiveness
  src/components/v2/Table/index.tsx
  src/components/v2/Table/styles.ts
  src/pages/Dashboard/Markets/BorrowMarket/BorrowMarketTable.tsx
  src/pages/Dashboard/Markets/BorrowMarket/BorrowingTable.tsx
  src/pages/Dashboard/Markets/SupplyMarket/SuppliedTable.tsx
  src/pages/Dashboard/Markets/SupplyMarket/SupplyMarketTable.tsx
  src/pages/Dashboard/Markets/SupplyMarket/styles.ts
  src/translation/translations/en.json
Labels: 0.4.0

#453 Improves tables responsiveness
  src/pages/Dashboard/Markets/BorrowMarket/BorrowingTable.tsx
  src/pages/Dashboard/Markets/BorrowMarket/styles.ts
  src/pages/Dashboard/Markets/SupplyMarket/styles.ts
  src/pages/Dashboard/Markets/styles.ts
Labels: 0.4.0

#455 Fix issue with long words on Vote screen
  src/components/Vote/VoteOverview/ProposalDetail.tsx
Labels: 0.4.0

#458 Format percent without decimals on borrow table
  src/pages/Dashboard/Markets/BorrowMarket/BorrowingTable.tsx
Labels: 0.4.0

#461 Numerator should be token value in dollars
  src/pages/Dashboard/Markets/BorrowMarket/BorrowingTable.tsx
Labels: 0.4.0

#463 Fix UI not refreshing after enabling token
  src/clients/api/mutations/approveToken.ts
  src/components/v2/EnableToken/index.tsx
  src/constants/allowanceAmountWei.ts
  src/pages/Dashboard/Markets/BorrowMarket/index.tsx
  src/pages/Dashboard/Markets/SupplyMarket/index.tsx
Labels: 0.4.0

#460 Remove token info from `EnableToken` component on MintRepayVai
  src/components/v2/EnableToken/index.stories.tsx
  src/components/v2/EnableToken/index.tsx
  src/components/v2/EnableToken/styles.ts
  src/pages/Dashboard/MintRepayVai/MintVai/index.spec.tsx
  src/pages/Dashboard/MintRepayVai/MintVai/index.tsx
  src/pages/Dashboard/MintRepayVai/RepayVai/index.spec.tsx
  src/pages/Dashboard/MintRepayVai/RepayVai/index.tsx
  src/pages/Dashboard/MintRepayVai/index.spec.tsx
  src/translation/translations/en.json
Labels: 0.4.0

#472 Always enable treasury balance query
  src/clients/api/queries/useUserMarketInfo.ts
Labels: 0.4.0

#467 Prevent users from supplying LUNA
  src/components/Basic/SupplyTabs/SupplyTab.tsx
  src/pages/Dashboard/Modals/SupplyWithdraw/SupplyWithdrawForm.tsx
  src/pages/Dashboard/Modals/SupplyWithdraw/index.spec.tsx
  src/pages/Dashboard/Modals/SupplyWithdraw/index.tsx
Labels: 0.4.0

#466 invert background colors on text-input
  src/components/v2/TextField/styles.ts
Labels: 0.4.0

#422 Wire up convert vrt
  src/clients/api/index.ts
  src/clients/api/queries/getBalanceOf.spec.ts
  src/clients/api/queries/getBalanceOf.ts
  src/clients/api/queries/getVrtConversionEndTime.spec.ts
  src/clients/api/queries/getVrtConversionEndTime.ts
  src/clients/api/queries/getVrtConversionRatio.spec.ts
  src/clients/api/queries/getXvsWithdrawableAmount.spec.ts
  src/clients/api/queries/getXvsWithdrawableAmount.ts
  src/clients/api/queries/useGetXvsWithdrawableAmount.ts
  src/components/v2/Layout/ClaimXvsRewardButton/index.spec.tsx
  src/components/v2/Layout/ClaimXvsRewardButton/index.tsx
  src/components/v2/Layout/constants.tsx
  src/components/v2/SuccessfulTransactionModal/index.stories.tsx
  src/components/v2/SuccessfulTransactionModal/index.tsx
  src/context/SuccessfulTransactionModalContext.tsx
  src/hooks/useConvertToReadableCoinString.ts
  src/pages/ConvertVrt/Convert/index.spec.tsx
  src/pages/ConvertVrt/Convert/index.tsx
  src/pages/ConvertVrt/Withdraw/index.spec.tsx
  src/pages/ConvertVrt/Withdraw/index.tsx
  src/pages/ConvertVrt/constants.ts
  src/pages/ConvertVrt/index.stories.tsx
  src/pages/ConvertVrt/index.tsx
  src/pages/ConvertVrt/styles.ts
  src/pages/Dashboard/MintRepayVai/MintVai/getReadableFeeVai.ts
  src/pages/Dashboard/MintRepayVai/MintVai/index.spec.tsx
  src/pages/Dashboard/MintRepayVai/MintVai/index.tsx
  src/pages/Dashboard/MintRepayVai/RepayVai/index.spec.tsx
  src/pages/Dashboard/MintRepayVai/RepayVai/index.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Borrow/index.spec.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Borrow/index.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Repay/index.spec.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Repay/index.tsx
  src/pages/Dashboard/Modals/SupplyWithdraw/index.spec.tsx
  src/pages/Dashboard/Modals/SupplyWithdraw/index.tsx
  src/translation/translations/en.json
  src/utilities/calculateCollateralValue.ts
  src/utilities/common.ts
  src/utilities/formatI18nextRelativetimeValues.spec.ts
  src/utilities/formatI18nextRelativetimeValues.ts
Labels: 0.5.0

#477 Allow users to close positions by repaying max amount with uint256
  src/clients/api/mutations/approveToken.spec.ts
  src/components/Basic/BorrowTabs/RepayBorrowTab.tsx
  src/components/Basic/SupplyTabs/SupplyTab.tsx
  src/components/Basic/VaiTabs/RepayVaiTab.tsx
  src/components/Vault/VestingVault/CardContent.tsx
  src/constants/maxUint256.ts
  src/pages/Dashboard/Modals/BorrowRepay/Repay/index.spec.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Repay/index.tsx
Labels: 0.4.0

#424 Chore: add back button to modal header
  src/components/v2/Modal/index.stories.tsx
  src/components/v2/Modal/index.tsx
  src/components/v2/Modal/styles.ts
  src/theme/MuiThemeProvider/muiTheme.ts
  src/types/mui.d.ts
Labels: enhancement

#488 Revert "only allow users to disable UST / Luna collateral (#486)"
  src/components/Dashboard/Market/SupplyMarket.tsx
Labels: hotfix

#459 Refactor Table and Card styles
  src/components/v2/Table/TableCards.tsx
  src/components/v2/Table/index.stories.tsx
  src/components/v2/Table/index.tsx
  src/components/v2/Table/styles.ts
  src/components/v2/Table/types.ts
  src/pages/Dashboard/Markets/BorrowMarket/BorrowMarketTable.tsx
  src/pages/Dashboard/Markets/BorrowMarket/BorrowingTable.tsx
  src/pages/Dashboard/Markets/BorrowMarket/index.spec.tsx
  src/pages/Dashboard/Markets/BorrowMarket/styles.ts
  src/pages/Dashboard/Markets/SupplyMarket/SuppliedTable.tsx
  src/pages/Dashboard/Markets/SupplyMarket/SupplyMarketTable.tsx
  src/pages/Dashboard/Markets/SupplyMarket/index.spec.tsx
  src/pages/Dashboard/Markets/SupplyMarket/styles.ts
  src/pages/Dashboard/Markets/styles.ts
Labels: 0.6.0

#485 Remove duplicated VRT link
  src/components/v2/Layout/constants.tsx
Labels: 0.4.0

#470 Add Market Table
  src/components/v2/Table/TableCards.tsx
  src/components/v2/Table/index.tsx
  src/components/v2/Table/styles.ts
  src/pages/Market/MarketTable/index.spec.tsx
  src/pages/Market/MarketTable/index.stories.tsx
  src/pages/Market/MarketTable/index.tsx
  src/pages/Market/MarketTable/styles.ts
  src/pages/Market/index.tsx
  src/pages/Market/styles.ts
  src/translation/translations/en.json
  src/types/mui.d.ts
  src/utilities/common.ts
Labels: 0.6.0

#517 Call toast with valid argument
  src/pages/Dashboard/Modals/BorrowRepay/Borrow/index.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Repay/index.tsx
Labels: 0.4.0

#519 Approve VAI with Unitroller as spender
  src/pages/Dashboard/MintRepayVai/MintVai/index.tsx
Labels: 0.4.0

#520 Fix modal buttons styles
  src/components/v2/Modal/styles.ts
Labels: 0.4.0

#522 Add tooltip explaining minted VAI is included in borrow limit used
  src/components/v2/ProgressBar/AccountHealth/index.tsx
  src/components/v2/ProgressBar/AccountHealth/styles.ts
  src/components/v2/ProgressBar/LabeledProgressBar/index.tsx
  src/translation/translations/en.json
Labels: 0.4.0

#523 Fix style of warning icon on Notice component
  src/components/v2/Notice/styles.ts
Labels: 0.4.0

#521 Fix market links
  src/containers/Main/Market/index.tsx
Labels: 0.4.0

#498 Update toast notification design
  package.json
  src/assets/styles/App.scss
  src/clients/web3/useAuth/index.ts
  src/components/Basic/Toast.tsx
  src/components/Vote/Proposals.tsx
  src/components/Vote/ProposerDetail/ProposerInfo.tsx
  src/components/index.ts
  src/components/v2/EnableToken/index.spec.tsx
  src/components/v2/Icon/icons/attention.tsx
  src/components/v2/Icon/index.stories.tsx
  src/components/v2/Layout/ClaimXvsRewardButton/index.tsx
  src/components/v2/Notice/index.tsx
  src/components/v2/Notice/styles.ts
  src/components/v2/Toast/index.stories.tsx
  src/components/v2/Toast/index.tsx
  src/components/v2/Toast/styles.ts
  src/containers/Main/Faucet.tsx
  src/containers/Main/VoteOverview.tsx
  src/context/AuthContext.tsx
  src/pages/App.tsx
  src/pages/ConvertVrt/Convert/index.tsx
  src/pages/ConvertVrt/Withdraw/index.tsx
  src/pages/Dashboard/Markets/SupplyMarket/index.tsx
  src/pages/Dashboard/MintRepayVai/MintVai/index.spec.tsx
  src/pages/Dashboard/MintRepayVai/MintVai/index.tsx
  src/pages/Dashboard/MintRepayVai/RepayVai/index.spec.tsx
  src/pages/Dashboard/MintRepayVai/RepayVai/index.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Borrow/index.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Repay/index.tsx
  src/pages/Dashboard/Modals/SupplyWithdraw/SupplyWithdrawForm.tsx
  src/testUtils/renderComponent.tsx
  src/theme/MuiThemeProvider/muiTheme.ts
  yarn.lock
Labels: enhancement

#527 Fix VAI vault
  src/components/Vault/BasicVault/VaiCard.tsx
  src/constants/daysPerYear.ts
Labels: 0.4.0

#528 fetch pending venus rewards data from contract instead of local computation
  src/clients/api/queries/getXvsReward/getVTokenData.spec.ts
  src/clients/api/queries/getXvsReward/getVTokenData.ts
  src/clients/api/queries/getXvsReward/index.spec.ts
  src/clients/api/queries/getXvsReward/index.ts
  src/clients/api/queries/useGetXvsReward.ts
  src/components/Vote/VotingWallet.tsx
  src/constants/contracts/abis/venusLens.json
  src/constants/contracts/addresses/main.json
  src/containers/Main/Vote/index.tsx
Labels: 0.4.0

#529 Add market detail navigation
  .eslintrc.js
  src/components/v2/Table/TableCards.tsx
  src/components/v2/Table/index.tsx
  src/components/v2/Table/styles.ts
  src/pages/Dashboard/Markets/BorrowMarket/BorrowMarketTable.tsx
  src/pages/Dashboard/Markets/BorrowMarket/BorrowingTable.tsx
  src/pages/Dashboard/Markets/SupplyMarket/SuppliedTable.tsx
  src/pages/Dashboard/Markets/SupplyMarket/SupplyMarketTable.tsx
  src/pages/Dashboard/Markets/SupplyMarket/index.tsx
  src/pages/Market/MarketTable/index.tsx
  src/pages/Xvs/Table/index.tsx
  src/theme/MuiThemeProvider/muiTheme.ts
  src/types/mui.d.ts
Labels: 0.6.0

#535 Automatically scroll to the top of the page on route change
  src/components/index.ts
  src/components/v2/ResetScrollOnRouteChange/index.tsx
  src/pages/App.tsx
Labels: 0.4.0

#530 Market Details screen - Wire up Interest Model chart
  src/__mocks__/models/vTokenApySimulations.ts
  src/clients/api/__mocks__/index.ts
  src/clients/api/index.ts
  src/clients/api/queries/__snapshots__/getVTokenApySimulations.spec.ts.snap
  src/clients/api/queries/getVTokenApySimulations.spec.ts
  src/clients/api/queries/getVTokenApySimulations.ts
  src/clients/api/queries/getVTokenBorrowRate.spec.ts
  src/clients/api/queries/getVTokenBorrowRate.ts
  src/clients/api/queries/getVTokenCash.spec.ts
  src/clients/api/queries/getVTokenCash.ts
  src/clients/api/queries/getVTokenInterestRateModel.spec.ts
  src/clients/api/queries/getVTokenInterestRateModel.ts
  src/clients/api/queries/getVTokenSupplyRate.spec.ts
  src/clients/api/queries/getVTokenSupplyRate.ts
  src/clients/api/queries/getXvsReward/index.ts
  src/clients/api/queries/useGetVTokenApySimulations.ts
  src/clients/api/queries/useGetVTokenCash.ts
  src/clients/api/queries/useGetVTokenInterestRateModel.ts
  src/components/MarketDetail/InterestRateModel.tsx
  src/components/v2/charts/InterestRateChart/index.tsx
  src/constants/compoundMantissa.ts
  src/constants/functionKey.ts
  src/containers/Main/XVS/index.tsx
  src/pages/MarketDetails/__mocks__/models.ts
  src/pages/MarketDetails/index.spec.tsx
  src/pages/MarketDetails/index.stories.tsx
  src/pages/MarketDetails/index.tsx
  src/pages/MarketDetails/useGetMarketData.ts
Labels: 0.6.0

#558 Add checkbox
  src/components/v2/Checkbox/index.stories.tsx
  src/components/v2/Checkbox/index.tsx
  src/components/v2/Checkbox/styles.ts
  src/components/v2/Icon/icons/checkboxBorder.tsx
  src/components/v2/Icon/icons/checked.tsx
  src/components/v2/Icon/icons/index.ts
Labels: 0.7.0

#556 Refactor table to set alignment per column
  src/components/v2/Table/Head.tsx
  src/components/v2/Table/index.tsx
  src/components/v2/Table/styles.ts
  src/pages/Dashboard/Markets/BorrowMarket/BorrowMarketTable.tsx
  src/pages/Dashboard/Markets/BorrowMarket/BorrowingTable.tsx
  src/pages/Dashboard/Markets/SupplyMarket/SuppliedTable.tsx
  src/pages/Dashboard/Markets/SupplyMarket/SupplyMarketTable.tsx
  src/pages/Market/MarketTable/index.tsx
  src/pages/Xvs/Table/index.tsx
Labels: 0.5.0

#549 Feature: Add pagination
  src/components/v2/Icon/icons/arrowRight.tsx
  src/components/v2/Pagination/index.stories.tsx
  src/components/v2/Pagination/index.tsx
  src/components/v2/Pagination/styles.ts
  src/components/v2/Pagination/usePagination.ts
  src/components/v2/Table/index.stories.tsx
  src/components/v2/Table/storiesUtils.tsx
  src/translation/translations/en.json
  src/types/mui.d.ts
Labels: 0.7.0

#569 Put back Vault page
  src/pages/App.tsx
Labels: 0.5.0

#560 Refactor EnableToken
  src/__mocks__/models/asset.ts
  src/clients/api/mutations/approveToken.spec.ts
  src/clients/api/mutations/approveToken.ts
  src/clients/api/mutations/useApproveToken/index.ts
  src/clients/api/mutations/useApproveToken/setCachedTokenAllowanceToMax.ts
  src/clients/api/queries/__snapshots__/useGetUserMarketInfo.spec.tsx.snap
  src/clients/api/queries/useGetAllowance.ts
  src/clients/api/queries/useGetUserMarketInfo.ts
  src/components/v2/EnableToken/index.spec.tsx
  src/components/v2/EnableToken/index.stories.tsx
  src/components/v2/EnableToken/index.tsx
  src/components/v2/EnableToken/styles.ts
  src/context/MarketContext.tsx
  src/pages/ConvertVrt/Convert/index.spec.tsx
  src/pages/ConvertVrt/Convert/index.tsx
  src/pages/ConvertVrt/index.stories.tsx
  src/pages/ConvertVrt/index.tsx
  src/pages/Dashboard/MintRepayVai/MintVai/index.spec.tsx
  src/pages/Dashboard/MintRepayVai/MintVai/index.tsx
  src/pages/Dashboard/MintRepayVai/RepayVai/index.spec.tsx
  src/pages/Dashboard/MintRepayVai/RepayVai/index.tsx
  src/pages/Dashboard/MintRepayVai/index.spec.tsx
  src/pages/Dashboard/MintRepayVai/index.stories.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Borrow/index.spec.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Borrow/index.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Repay/index.spec.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Repay/index.tsx
  src/pages/Dashboard/Modals/BorrowRepay/index.stories.tsx
  src/pages/Dashboard/Modals/SupplyWithdraw/index.spec.tsx
  src/pages/Dashboard/Modals/SupplyWithdraw/index.stories.tsx
  src/pages/Dashboard/Modals/SupplyWithdraw/index.tsx
  src/stories/decorators.tsx
  src/types/index.ts
  src/utilities/getTokenSpenderAddress.ts
  src/utilities/index.ts
Labels: 0.5.0

#565 Minor design and translation fixes
  src/components/v2/ConnectWallet/index.tsx
  src/components/v2/ConnectWallet/styles.ts
  src/components/v2/Tabs/styles.tsx
  src/pages/ConvertVrt/Convert/index.tsx
  src/pages/ConvertVrt/styles.ts
  src/translation/translations/en.json
Labels: 0.5.0

#571 Convert VRT - Hide available XVS when token needs enabling
  src/pages/ConvertVrt/Convert/index.spec.tsx
  src/pages/ConvertVrt/Convert/index.tsx
  src/pages/ConvertVrt/Withdraw/index.tsx
  src/pages/ConvertVrt/index.stories.tsx
  src/pages/ConvertVrt/index.tsx
  src/pages/ConvertVrt/styles.ts
Labels: 0.5.0

#566 Update common utils
  src/pages/Dashboard/Markets/BorrowMarket/BorrowMarketTable.tsx
  src/pages/Dashboard/Markets/BorrowMarket/BorrowingTable.tsx
  src/pages/Dashboard/Markets/SupplyMarket/SuppliedTable.tsx
  src/pages/Dashboard/Markets/SupplyMarket/SupplyMarketTable.tsx
  src/pages/Dashboard/Modals/SupplyWithdraw/SupplyWithdrawForm.tsx
  src/pages/History/HistoryTable/index.tsx
  src/pages/Market/MarketTable/index.tsx
  src/pages/MarketDetails/__snapshots__/index.spec.tsx.snap
  src/pages/MarketDetails/index.tsx
  src/pages/Xvs/Header/index.tsx
  src/pages/Xvs/Table/index.tsx
  src/utilities/common.spec.ts
  src/utilities/common.ts
Labels: 0.6.0

#572 Fix typo on tooltip in Vote page
  src/containers/Main/VoteOverview.tsx
Labels: 0.5.0

#574 Fix redirection issue
  src/components/v2/ResetScrollOnRouteChange/index.tsx
  src/pages/App.tsx
Labels: 0.5.0

#575 Verify safe limit is greater than borrowed amount
  src/pages/Dashboard/Modals/BorrowRepay/Borrow/index.tsx
Labels: 0.5.0

#579 Refresh withdrawable XVS after successful withdraw
  src/clients/api/mutations/useWithdrawXvs.ts
Labels: 0.5.0

#584 Fix conversion rate on Convert VRT page
  src/pages/ConvertVrt/constants.ts
  src/pages/ConvertVrt/index.tsx
Labels: hotfix
