Repository VenusProtocol/venus-protocol-interface, pull requests merged in 2022-06, with the labels that each got.

#552 Update transaction error translations
  .storybook/preview.js
  src/clients/api/mutations/borrowVToken.spec.ts
  src/clients/api/mutations/borrowVToken.ts
  src/clients/api/mutations/claimXvsReward.spec.ts
  src/clients/api/mutations/claimXvsReward.ts
  src/clients/api/mutations/enterMarkets.spec.ts
  src/clients/api/mutations/enterMarkets.ts
  src/clients/api/mutations/exitMarket.spec.ts
  src/clients/api/mutations/exitMarket.ts
  src/clients/api/mutations/mintVai.spec.ts
  src/clients/api/mutations/mintVai.ts
  src/clients/api/mutations/redeem.spec.ts
  src/clients/api/mutations/redeem.ts
  src/clients/api/mutations/redeemUnderlying.spec.ts
  src/clients/api/mutations/redeemUnderlying.ts
  src/clients/api/mutations/repayBnb.ts
  src/clients/api/mutations/repayNonBnbVToken.ts
  src/clients/api/mutations/repayVai.spec.ts
  src/clients/api/mutations/repayVai.ts
  src/clients/api/mutations/supplyBnb.spec.ts
  src/clients/api/mutations/supplyBnb.ts
  src/clients/api/mutations/supplyNonBnb.spec.ts
  src/clients/api/mutations/supplyNonBnb.ts
  src/components/v2/Layout/ClaimXvsRewardButton/index.tsx
  src/errors/VError.ts
  src/errors/formatVErrorToReadableString.ts
  src/errors/index.ts
  src/errors/interactionErrorPhrases.ts
  src/errors/transactionErrorPhrases.ts
  src/errors/transactionErrors.ts
  src/errors/unexpectedErrorPhrases.ts
  src/pages/App.tsx
  src/pages/ConvertVrt/Convert/index.tsx
  src/pages/ConvertVrt/index.tsx
  src/pages/Dashboard/Markets/SupplyMarket/index.tsx
  src/pages/Dashboard/MintRepayVai/MintVai/index.tsx
  src/pages/Dashboard/MintRepayVai/RepayVai/index.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Borrow/index.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Repay/index.tsx
  src/pages/Dashboard/Modals/SupplyWithdraw/SupplyWithdrawForm.tsx
  src/testUtils/renderComponent.tsx
  src/translation/index.tsx
  src/translation/transactionErrors.ts
  src/translation/translations/en.json
Labels: 0.6.0

#581 Vault - Transaction form
  src/hooks/useConvertToReadableCoinString.ts
  src/pages/ConvertVrt/Convert/index.tsx
  src/pages/Vault/TransactionForm/index.stories.tsx
  src/pages/Vault/TransactionForm/index.tsx
  src/pages/Vault/TransactionForm/styles.ts
  src/translation/translations/en.json
  src/utilities/common.ts
  src/utilities/formatI18nextRelativetimeValues.spec.ts
  src/utilities/formatI18nextRelativetimeValues.ts
  src/utilities/index.ts
Labels: 0.8.0

#561 Add vote proposal card UI
  package.json
  src/components/v2/Icon/icons/check.tsx
  src/components/v2/Icon/icons/dots.tsx
  src/components/v2/Icon/icons/exclamation.tsx
  src/components/v2/Icon/icons/index.ts
  src/components/v2/ProgressBar/index.stories.tsx
  src/components/v2/ProgressBar/index.tsx
  src/components/v2/ProgressBar/styles.ts
  src/components/v2/VoteProposalUi/ActiveVotingProgress/index.tsx
  src/components/v2/VoteProposalUi/index.stories.tsx
  src/components/v2/VoteProposalUi/index.tsx
  src/components/v2/VoteProposalUi/styles.ts
  src/theme/MuiThemeProvider/muiTheme.ts
  src/translation/translations/en.json
  src/types/mui.d.ts
  yarn.lock
Labels: enhancement, 0.9.0

#602 Claim rewards for all address
  src/clients/api/mutations/claimXvsReward.spec.ts
  src/clients/api/mutations/claimXvsReward.ts
  src/clients/api/mutations/useClaimXvsReward.ts
Labels: 0.6.0

#603 Use Maximillion contract when repaying BNB loan in full
  src/clients/api/mutations/repayBnb.spec.ts
  src/clients/api/mutations/repayBnb.ts
  src/clients/api/mutations/repayNonBnbVToken.spec.ts
  src/clients/api/mutations/repayNonBnbVToken.ts
  src/clients/contracts/__mocks__/index.ts
  src/clients/contracts/getters.ts
  src/components/v2/Notice/styles.ts
  src/config/abis/comptrollerLens.json
  src/config/contracts.ts
  src/constants/contracts/abis/maximillion.json
  src/constants/contracts/addresses/main.json
  src/pages/Dashboard/Modals/BorrowRepay/Borrow/index.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Borrow/styles.ts
  src/pages/Dashboard/Modals/BorrowRepay/Repay/index.spec.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Repay/index.tsx
  src/pages/Dashboard/Modals/styles.ts
  src/pages/MarketDetails/index.stories.tsx
  src/pages/MarketDetails/index.tsx
  src/pages/MarketDetails/useGetMarketData.ts
  src/translation/translations/en.json
  src/types/contracts/index.ts
Labels: 0.6.0

#601 Fetch the VAI staked without waiting for a wallet to connect
  src/pages/Xvs/Table/index.tsx
Labels: 0.6.0

#604 Display full repayment warning for all tokens
  src/pages/Dashboard/Modals/BorrowRepay/Repay/index.spec.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Repay/index.tsx
  src/translation/translations/en.json
Labels: 0.6.0

#605 Remove old XVS page + update package number to 0.6.0
  package.json
  src/containers/Main/XVS/index.stories.tsx
  src/containers/Main/XVS/index.tsx
  src/pages/App.tsx
Labels: 0.6.0

#606 Use Vault contract to get voting power
  src/containers/Main/VoteOverview.tsx
Labels: 0.6.0

#607 0.6.0 - Fixes
  src/clients/api/queries/getAssetsInAccount.ts
  src/clients/api/queries/useGetAllowance.ts
  src/clients/api/queries/useGetAssetsInAccount.ts
  src/clients/api/queries/useGetBalanceOf.ts
  src/clients/api/queries/useGetMintedVai.ts
  src/clients/api/queries/useGetUserMarketInfo.ts
  src/clients/api/queries/useGetVTokenBalanceOf.ts
  src/clients/api/queries/useGetVTokenBorrowBalance.ts
  src/clients/api/queries/useGetXvsReward.ts
  src/components/v2/ProgressBar/LabeledProgressBar/styles.tsx
  src/pages/Market/MarketTable/index.tsx
  src/pages/Xvs/Header/index.tsx
Labels: 0.6.0

#608 Use wei values in XVS page and related hooks
  src/clients/api/__mocks__/index.ts
  src/clients/api/index.ts
  src/clients/api/queries/__snapshots__/useGetUserMarketInfo.spec.tsx.snap
  src/clients/api/queries/getMarkets.ts
  src/clients/api/queries/getVenusVaiVaultDailyRateWei.spec.ts
  src/clients/api/queries/getVenusVaiVaultDailyRateWei.ts
  src/clients/api/queries/getVenusVaiVaultRate.ts
  src/clients/api/queries/useGetUserMarketInfo.spec.tsx
  src/clients/api/queries/useGetUserMarketInfo.ts
  src/clients/api/queries/useGetVenusVaiVaultDailyRateWei.ts
  src/clients/api/queries/useGetVenusVaiVaultRate.ts
  src/constants/functionKey.ts
  src/pages/Market/MarketTable/index.tsx
  src/pages/Xvs/Header/index.tsx
  src/pages/Xvs/Table/index.tsx
  src/pages/Xvs/index.spec.tsx
Labels: 0.6.0

#609 Update column header on market page
  src/pages/Market/MarketTable/index.tsx
  src/translation/translations/en.json
Labels: 0.6.0

#593 Rethrow vError and format a nice message on collateral toggle contract errors
  package.json
  src/containers/Main/VoteOverview.tsx
  src/containers/Main/XVS/index.stories.tsx
  src/containers/Main/XVS/index.tsx
  src/errors/VError.ts
  src/errors/formatVErrorToReadableString.ts
  src/errors/transactionErrors.ts
  src/pages/App.tsx
  src/pages/Dashboard/Markets/SupplyMarket/index.tsx
Labels: 0.6.0

#599 Add treasury total hook for Market page
  src/__mocks__/models/asset.ts
  src/__mocks__/models/markets.ts
  src/clients/api/__mocks__/index.ts
  src/clients/api/index.ts
  src/clients/api/queries/__snapshots__/useGetTreasuryTotals.spec.tsx.snap
  src/clients/api/queries/__snapshots__/useGetUserMarketInfo.spec.tsx.snap
  src/clients/api/queries/getMarkets.ts
  src/clients/api/queries/useGetTreasuryTotals.spec.tsx
  src/clients/api/queries/useGetTreasuryTotals.ts
  src/clients/api/queries/useGetUserMarketInfo.spec.tsx
  src/clients/api/queries/useGetUserMarketInfo.ts
  src/context/MarketContext.tsx
  src/pages/Dashboard/Modals/SupplyWithdraw/SupplyWithdrawForm.tsx
  src/pages/Market/Header/index.tsx
  src/pages/Market/MarketTable/index.tsx
  src/pages/Market/index.spec.tsx
  src/pages/MarketDetails/index.spec.tsx
  src/types/index.ts
Labels: 0.6.0

#613 Minimize decimals of XVS reward
  src/components/v2/Layout/ClaimXvsRewardButton/index.spec.tsx
  src/components/v2/Layout/ClaimXvsRewardButton/index.tsx
Labels: 0.6.0

#583 Add delegate voting modal
  src/components/v2/Form/FormikTextField.tsx
  src/components/v2/Form/index.ts
  src/components/v2/Modal/index.tsx
  src/components/v2/Modal/styles.ts
  src/pages/Vote/DelegateModal/addressValidationSchema.ts
  src/pages/Vote/DelegateModal/index.stories.tsx
  src/pages/Vote/DelegateModal/index.tsx
  src/pages/Vote/DelegateModal/styles.ts
  src/translation/translations/en.json
Labels: 0.9.0

#618 Update design of banner
  src/components/v2/Layout/Banner/index.tsx
  src/components/v2/Layout/Banner/styles.ts
Labels: hotfix

#587 Vote UI requests
  src/__mocks__/api/proposals.json
  src/__mocks__/models/proposals.ts
  src/clients/api/__mocks__/index.ts
  src/clients/api/index.ts
  src/clients/api/queries/getCurrentVotes.spec.ts
  src/clients/api/queries/getCurrentVotes.ts
  src/clients/api/queries/getPendingXvs.spec.ts
  src/clients/api/queries/getPendingXvs.ts
  src/clients/api/queries/getProposals/__snapshots__/index.spec.ts.snap
  src/clients/api/queries/getProposals/formatToProposal.ts
  src/clients/api/queries/getProposals/index.spec.ts
  src/clients/api/queries/getProposals/index.ts
  src/clients/api/queries/getProposals/types.ts
  src/clients/api/queries/getVTokenApySimulations.ts
  src/clients/api/queries/getVenusVaiVaultDailyRateWei.spec.ts
  src/clients/api/queries/getVenusVaiVaultDailyRateWei.ts
  src/clients/api/queries/getVoteReceipt.spec.ts
  src/clients/api/queries/getVoteReceipt.ts
  src/clients/api/queries/useGetCurrentVotes.ts
  src/clients/api/queries/useGetPendingXvs.ts
  src/clients/api/queries/useGetProposals.ts
  src/clients/api/queries/useGetVaults/index.ts
  src/clients/api/queries/useGetVoteReceipt.ts
  src/components/Basic/Proposal.tsx
  src/components/Basic/Voting.tsx
  src/components/Vault/BasicVault/VaiCard.tsx
  src/components/Vote/Proposals.tsx
  src/components/Vote/VoteOverview/ProposalDetail.tsx
  src/components/Vote/VoteOverview/ProposalHistory.tsx
  src/components/Vote/VoteOverview/ProposalInfo.tsx
  src/components/Vote/VoteOverview/ProposalUser.tsx
  src/components/Vote/types/index.ts
  src/constants/blocksPerDay.ts
  src/constants/bsc.ts
  src/constants/functionKey.ts
  src/containers/Main/VoteOverview.tsx
  src/errors/VError.ts
  src/errors/unexpectedErrorPhrases.ts
  src/translation/translations/en.json
  src/types/index.ts
Labels: 0.9.0

#610 [VEN-228] Vault - Fetch VAI vault
  src/__mocks__/models/vaults.ts
  src/clients/api/__mocks__/index.ts
  src/clients/api/index.ts
  src/clients/api/queries/getMarkets.ts
  src/clients/api/queries/getVaiVaultPendingXvsWei.spec.ts
  src/clients/api/queries/getVaiVaultPendingXvsWei.ts
  src/clients/api/queries/getVaiVaultUserInfo.spec.ts
  src/clients/api/queries/getVaiVaultUserInfo.ts
  src/clients/api/queries/useGetBalanceOf.ts
  src/clients/api/queries/useGetVaiVaultPendingXvsWei.ts
  src/clients/api/queries/useGetVaiVaultUserInfo.ts
  src/clients/api/queries/useGetVaults/__snapshots__/index.spec.tsx.snap
  src/clients/api/queries/useGetVaults/constants.ts
  src/clients/api/queries/useGetVaults/index.spec.tsx
  src/clients/api/queries/useGetVaults/index.ts
  src/clients/api/queries/useGetVaults/useGetVaiVault.ts
  src/clients/api/queries/useGetVaults/useGetVestingVaults/index.ts
  src/clients/api/queries/useGetVaults/useGetVestingVaults/useGetXvsVaultPoolBalances.ts
  src/clients/api/queries/useGetVaults/useGetVestingVaults/useGetXvsVaultPools.ts
  src/clients/api/queries/useGetVenusVaiVaultDailyRateWei.ts
  src/constants/functionKey.ts
  src/pages/Vault/index.stories.tsx
  src/pages/Vault/index.tsx
  src/types/index.ts
Labels: 0.8.0

#595 [VEN-228] Vault - List vesting vaults + VAI vault
  src/__mocks__/contracts/comptroller.ts
  src/__mocks__/contracts/vaiVault.ts
  src/__mocks__/contracts/xvsVault.ts
  src/__mocks__/models/vaults.ts
  src/clients/api/__mocks__/index.ts
  src/clients/api/index.ts
  src/clients/api/queries/getMarkets.ts
  src/clients/api/queries/getVaiVaultPendingXvsWei.spec.ts
  src/clients/api/queries/getVaiVaultPendingXvsWei.ts
  src/clients/api/queries/getVaiVaultUserInfo/__snapshots__/index.spec.ts.snap
  src/clients/api/queries/getVaiVaultUserInfo/formatToUserInfo.ts
  src/clients/api/queries/getVaiVaultUserInfo/index.spec.ts
  src/clients/api/queries/getVaiVaultUserInfo/index.ts
  src/clients/api/queries/getVaiVaultUserInfo/types.ts
  src/clients/api/queries/getXvsVaultPoolInfo/__snapshots__/index.spec.ts.snap
  src/clients/api/queries/getXvsVaultPoolInfo/formatToPoolInfo.ts
  src/clients/api/queries/getXvsVaultPoolInfo/index.spec.ts
  src/clients/api/queries/getXvsVaultPoolInfo/index.ts
  src/clients/api/queries/getXvsVaultPoolInfo/types.ts
  src/clients/api/queries/getXvsVaultPoolInfos.ts
  src/clients/api/queries/getXvsVaultUserInfo.ts
  src/clients/api/queries/getXvsVaultUserInfo/__snapshots__/index.spec.ts.snap
  src/clients/api/queries/getXvsVaultUserInfo/formatToUserInfo.ts
  src/clients/api/queries/getXvsVaultUserInfo/index.spec.ts
  src/clients/api/queries/getXvsVaultUserInfo/index.ts
  src/clients/api/queries/getXvsVaultUserInfo/types.ts
  src/clients/api/queries/useGetBalanceOf.ts
  src/clients/api/queries/useGetVaiVaultPendingXvsWei.ts
  src/clients/api/queries/useGetVaiVaultUserInfo.ts
  src/clients/api/queries/useGetVaults/__snapshots__/index.spec.tsx.snap
  src/clients/api/queries/useGetVaults/constants.ts
  src/clients/api/queries/useGetVaults/index.spec.tsx
  src/clients/api/queries/useGetVaults/index.ts
  src/clients/api/queries/useGetVaults/useGetVaiVault.ts
  src/clients/api/queries/useGetVaults/useGetVestingVaults/index.ts
  src/clients/api/queries/useGetVaults/useGetVestingVaults/useGetXvsVaultPoolBalances.ts
  src/clients/api/queries/useGetVaults/useGetVestingVaults/useGetXvsVaultPools.ts
  src/clients/api/queries/useGetVenusVaiVaultDailyRateWei.ts
  src/clients/api/queries/useGetXvsVaultPoolsCount.ts
  src/clients/api/queries/useGetXvsVaultRewardWeiPerBlock.ts
  src/clients/api/queries/useGetXvsVaultTotalAllocationPoints.ts
  src/components/v2/VaultItemUi/index.tsx
  src/constants/functionKey.ts
  src/hooks/useConvertToReadableCoinString.ts
  src/pages/Vault/VaultItem/index.stories.tsx
  src/pages/Vault/VaultItem/index.tsx
  src/pages/Vault/VaultItem/styles.ts
  src/pages/Vault/__snapshots__/index.spec.tsx.snap
  src/pages/Vault/index.spec.tsx
  src/pages/Vault/index.stories.tsx
  src/pages/Vault/index.tsx
  src/pages/Vault/styles.ts
  src/translation/translations/en.json
  src/types/index.ts
  src/utilities/common.ts
Labels: 0.8.0

#633 Capitalize column header text + update side menu items order
  src/components/v2/Layout/constants.tsx
  src/pages/App.tsx
  src/translation/translations/en.json
Labels: 0.7.0

#637 Fix reserve and collateral factors calculation
  src/pages/MarketDetails/useGetMarketData.ts
Labels: 0.7.0

#640 [VEN-282] Add modal to warn users to decollateralize LUNA and UST
  src/pages/Dashboard/Modals/LunaUstWarning/index.tsx
  src/pages/Dashboard/Modals/LunaUstWarning/styles.ts
  src/pages/Dashboard/Modals/index.ts
  src/pages/Dashboard/index.spec.tsx
  src/pages/Dashboard/index.tsx
  src/pages/Dashboard/useLunaUstWarningModal.ts
  src/translation/translations/en.json
Labels: 0.7.0

#631 Transaction fetching improvements
  src/__mocks__/models/transactions.ts
  src/clients/api/queries/getTransactions/formatTransaction.ts
  src/clients/api/queries/getTransactions/index.spec..ts
  src/clients/api/queries/getTransactions/index.ts
  src/clients/api/queries/getTransactions/types.ts
  src/components/v2/Table/index.tsx
  src/models/Transaction.ts
  src/models/index.ts
  src/pages/History/HistoryTable/index.tsx
  src/pages/History/index.tsx
  src/types/index.ts
Labels: 0.7.0

#639 History screen fixes
  src/components/v2/Checkbox/styles.ts
  src/components/v2/Table/index.tsx
  src/components/v2/Table/styles.ts
  src/pages/History/Filters/index.tsx
  src/pages/History/Filters/styles.ts
  src/pages/History/HistoryTable/index.tsx
  src/pages/History/index.spec.tsx
  src/pages/History/styles.ts
  src/pages/Market/styles.ts
Labels: 0.7.0

#644 Add header bottom margin
  src/pages/Market/styles.ts
Labels: 0.7.0

#648 Add asset name to collateral modal
  src/pages/Dashboard/Markets/SupplyMarket/CollateralConfirmModal/index.tsx
  src/translation/translations/en.json
Labels: 0.7.0

#628 [VEN-226] [VEN-227] [VEN-217] Wire up vote page
  src/clients/api/__mocks__/index.ts
  src/clients/api/index.ts
  src/clients/api/mutations/setVoteDelegate.spec.ts
  src/clients/api/mutations/setVoteDelegate.ts
  src/clients/api/mutations/useSetVoteDelegate.ts
  src/clients/api/queries/getProposals/__snapshots__/index.spec.ts.snap
  src/clients/api/queries/getProposals/formatToProposal.ts
  src/clients/api/queries/getProposals/index.spec.ts
  src/clients/api/queries/getProposals/index.ts
  src/clients/api/queries/getProposals/types.ts
  src/clients/api/queries/getVoteDelegateAddress.spec.ts
  src/clients/api/queries/getVoteDelegateAddress.ts
  src/clients/api/queries/useGetCurrentVotes.ts
  src/clients/api/queries/useGetVoteDelegateAddress.ts
  src/components/v2/GovernanceProposal/index.stories.tsx
  src/components/v2/GovernanceProposal/index.tsx
  src/constants/address.ts
  src/constants/functionKey.ts
  src/errors/unexpectedErrorPhrases.ts
  src/pages/Vote/DelegateModal/index.stories.tsx
  src/pages/Vote/DelegateModal/index.tsx
  src/pages/Vote/Governance/index.tsx
  src/pages/Vote/Governance/styles.ts
  src/pages/Vote/VotingWallet/index.tsx
  src/pages/Vote/VotingWallet/styles.ts
  src/pages/Vote/index.spec.tsx
  src/pages/Vote/styles.ts
  src/translation/translations/en.json
Labels: 0.8.0

#649 Fix UST LUNA warning modal
  src/pages/Dashboard/useLunaUstWarningModal.ts
Labels: 0.7.0

#647 Add errors to translation strings and improve wallet mismatch error
  src/clients/web3/useAuth/index.ts
  src/translation/translations/en.json
Labels: 0.7.0

#652 Remove old history path
  src/constants/path.ts
  src/pages/App.tsx
Labels: 0.7.0

#653 Fix sorting on Table
  src/components/v2/Table/index.tsx
  src/pages/History/HistoryTable/index.tsx
Labels: 0.7.0

#655 Add missing dependency to useEffect
  src/components/v2/Pagination/usePagination.ts
Labels: 0.7.0

#630 Chore: apy to apr calculating
  src/clients/api/__mocks__/index.ts
  src/clients/api/index.ts
  src/clients/api/queries/getDailyXvsWei.ts
  src/clients/api/queries/useGetDailyXvsWei.ts
  src/constants/contracts/abis/venusLens.json
  src/constants/contracts/addresses/main.json
  src/constants/functionKey.ts
  src/hooks/useDailyXvsWei.ts
  src/pages/Dashboard/Modals/BorrowRepay/AccountData/index.tsx
  src/pages/Dashboard/Modals/SupplyWithdraw/SupplyWithdrawForm.tsx
  src/pages/Dashboard/MyAccount/index.tsx
  src/pages/Dashboard/index.tsx
  src/types/contracts/VenusLens.ts
  src/utilities/calculateYearlyEarnings.spec.ts
  src/utilities/calculateYearlyEarnings.ts
Labels: 0.8.0

#659 [VEN-286] Integrate Infinity Wallet
  package.json
  src/assets/img/v2/wallets/infinityWalletLogo.svg
  src/clients/web3/connectors.ts
  src/clients/web3/types.ts
  src/clients/web3/useAuth/index.ts
  src/components/v2/AuthModal/constants.ts
  src/translation/translations/en.json
  yarn.lock
Labels: 0.8.0

#650 [VEN-228] Claim vault rewards mutations
  src/clients/api/__mocks__/index.ts
  src/clients/api/index.ts
  src/clients/api/mutations/claimVaiVaultReward.spec.ts
  src/clients/api/mutations/claimVaiVaultReward.ts
  src/clients/api/mutations/claimVrtVaultReward.spec.ts
  src/clients/api/mutations/claimVrtVaultReward.ts
  src/clients/api/mutations/claimXvsVaultReward.spec.ts
  src/clients/api/mutations/claimXvsVaultReward.ts
  src/clients/api/mutations/mintVai.spec.ts
  src/clients/api/mutations/repayVai.spec.ts
  src/clients/api/mutations/useClaimVaiVaultReward.ts
  src/clients/api/mutations/useClaimVrtVaultReward.ts
  src/clients/api/mutations/useClaimXvsVaultReward.ts
  src/clients/api/queries/useGetVaiVaultPendingXvsWei.ts
  src/constants/contracts/errorReporter.ts
  src/constants/functionKey.ts
  src/errors/transactionErrorPhrases.ts
  src/errors/transactionErrors.ts
Labels: 0.9.0

#666 [VEN-269] Add collateral factor column to Market page
  src/constants/smartContractPercentageDecimal.ts
  src/pages/Market/MarketTable/index.tsx
  src/pages/MarketDetails/useGetMarketData.ts
  src/translation/translations/en.json
  src/utilities/convertPercentageFromSmartContract.ts
  src/utilities/index.ts
Labels: 0.8.0

#662 [VEN-228] Fetch VRT vault
  src/__mocks__/contracts/vrtVault.ts
  src/clients/api/__mocks__/index.ts
  src/clients/api/index.ts
  src/clients/api/queries/getPendingXvs.spec.ts
  src/clients/api/queries/getPendingXvs.ts
  src/clients/api/queries/getVrtVaultAccruedInterestWei.spec.ts
  src/clients/api/queries/getVrtVaultAccruedInterestWei.ts
  src/clients/api/queries/getVrtVaultInterestRatePerBlock.spec.ts
  src/clients/api/queries/getVrtVaultInterestRatePerBlock.ts
  src/clients/api/queries/getVrtVaultUserInfo/__snapshots__/index.spec.ts.snap
  src/clients/api/queries/getVrtVaultUserInfo/formatToUserInfo.ts
  src/clients/api/queries/getVrtVaultUserInfo/index.spec.ts
  src/clients/api/queries/getVrtVaultUserInfo/index.ts
  src/clients/api/queries/getVrtVaultUserInfo/types.ts
  src/clients/api/queries/useGetPendingXvs.ts
  src/clients/api/queries/useGetVaults/__snapshots__/index.spec.tsx.snap
  src/clients/api/queries/useGetVaults/index.spec.tsx
  src/clients/api/queries/useGetVaults/index.ts
  src/clients/api/queries/useGetVaults/useGetVaiVault.ts
  src/clients/api/queries/useGetVaults/useGetVrtVault.ts
  src/clients/api/queries/useGetVrtVaultAccruedInterestWei.ts
  src/clients/api/queries/useGetVrtVaultInterestRatePerBlock.ts
  src/clients/api/queries/useGetVrtVaultUserInfo.ts
  src/constants/functionKey.ts
Labels: 0.9.0

#646 Create proposal UI
  src/components/index.ts
  src/components/v2/Accordion/index.tsx
  src/components/v2/Accordion/styles.ts
  src/components/v2/Countdown/styles.ts
  src/components/v2/Form/FormikMarkdownEditor.tsx
  src/components/v2/Form/FormikTextField.tsx
  src/components/v2/Form/FormikTokenTextField.tsx
  src/components/v2/Form/index.ts
  src/components/v2/Icon/icons/arrowDown.tsx
  src/components/v2/Markdown/Editor/index.stories.tsx
  src/components/v2/Markdown/Editor/index.tsx
  src/components/v2/Markdown/Editor/styles-overrides.scss
  src/components/v2/Markdown/Editor/styles.ts
  src/components/v2/Markdown/Viewer/index.tsx
  src/components/v2/Markdown/index.ts
  src/components/v2/Modal/styles.ts
  src/components/v2/TextField/styles.ts
  src/pages/Vote/CreateProposalModal/ActionAccordion/CallDataFields.tsx
  src/pages/Vote/CreateProposalModal/ActionAccordion/index.tsx
  src/pages/Vote/CreateProposalModal/ActionAccordion/styles.ts
  src/pages/Vote/CreateProposalModal/ProposalPreview/getContractName.ts
  src/pages/Vote/CreateProposalModal/ProposalPreview/index.tsx
  src/pages/Vote/CreateProposalModal/ProposalPreview/styles.ts
  src/pages/Vote/CreateProposalModal/index.spec.tsx
  src/pages/Vote/CreateProposalModal/index.stories.tsx
  src/pages/Vote/CreateProposalModal/index.tsx
  src/pages/Vote/CreateProposalModal/proposalSchema.ts
  src/pages/Vote/CreateProposalModal/styles.ts
  src/pages/Vote/DelegateModal/addressValidationSchema.ts
  src/pages/Vote/Governance/index.tsx
  src/translation/translations/en.json
  src/utilities/index.ts
  src/utilities/parseFunctionSignature.ts
  yarn.lock
Labels: 0.8.0

#686 Display borrow cap in tokens
  src/pages/Market/styles.ts
  src/pages/MarketDetails/index.stories.tsx
  src/pages/MarketDetails/index.tsx
  src/pages/MarketDetails/useGetMarketData.ts
Labels: hotfix

#692 Fix function key
  src/clients/api/index.ts
  src/clients/api/mutations/useApproveToken.ts
  src/clients/api/queries/getAllowance/index.spec.ts
  src/clients/api/queries/getAllowance/index.ts
  src/clients/api/queries/getAllowance/setCachedTokenAllowanceToMax.ts
  src/clients/api/queries/getAllowance/useGetAllowance.ts
  src/components/v2/EnableToken/index.spec.tsx
  src/components/v2/EnableToken/index.tsx
  src/pages/ConvertVrt/Convert/index.spec.tsx
  src/pages/Dashboard/MintRepayVai/MintVai/index.spec.tsx
  src/pages/Dashboard/MintRepayVai/RepayVai/index.spec.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Borrow/index.spec.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Repay/index.spec.tsx
  src/pages/Dashboard/Modals/SupplyWithdraw/index.spec.tsx
  src/stories/decorators.tsx
Labels: hotfix

#694 [VEN-248] Wire up withdraw buttons on non vesting vaults (VAI and VRT)
  src/__mocks__/contracts/vaiVault.ts
  src/clients/api/__mocks__/index.ts
  src/clients/api/queries/getVaiVaultUserInfo/__snapshots__/index.spec.ts.snap
  src/clients/api/queries/useGetVaults/__snapshots__/index.spec.tsx.snap
  src/components/v2/Layout/ClaimXvsRewardButton/index.tsx
  src/constants/functionKey.ts
  src/constants/testIds.ts
  src/context/SuccessfulTransactionModalContext.tsx
  src/hooks/useHandleTransactionMutation.ts
  src/hooks/useSuccessfulTransactionModal.ts
  src/pages/ConvertVrt/Convert/index.tsx
  src/pages/ConvertVrt/Withdraw/index.tsx
  src/pages/ConvertVrt/index.tsx
  src/pages/Dashboard/MintRepayVai/MintVai/index.spec.tsx
  src/pages/Dashboard/MintRepayVai/MintVai/index.tsx
  src/pages/Dashboard/MintRepayVai/RepayVai/index.spec.tsx
  src/pages/Dashboard/MintRepayVai/RepayVai/index.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Borrow/index.tsx
  src/pages/Vault/TransactionForm/index.tsx
  src/pages/Vault/VaultItem/index.spec.tsx
  src/pages/Vault/VaultItem/index.tsx
  src/pages/Vault/modals/WithdrawFromVaiVaultModal/__snapshots__/index.spec.tsx.snap
  src/pages/Vault/modals/WithdrawFromVaiVaultModal/index.spec.tsx
  src/pages/Vault/modals/WithdrawFromVaiVaultModal/index.stories.tsx
  src/pages/Vault/modals/WithdrawFromVaiVaultModal/index.tsx
  src/pages/Vault/modals/index.ts
  src/translation/translations/en.json
Labels: 0.9.0

#703 Add hooks for copying
  src/context/AuthContext.tsx
  src/hooks/useCopyToClipoard.ts
  src/pages/Xvs/Header/index.tsx
  src/translation/translations/en.json
Labels: 0.7.1

#702 Better responsive card for market page
  src/pages/Market/MarketTable/index.tsx
  src/pages/Market/MarketTable/styles.ts
  src/pages/Market/styles.ts
Labels: 0.7.1

#705 Render italic in markdown preview
  src/components/v2/Markdown/previewOptions.ts
Labels: 0.8.0

#704 Remove check if form is dirty
  src/components/v2/Form/FormikSubmitButton.tsx
  src/containers/AmountForm/index.tsx
  src/pages/Vote/CreateProposalModal/index.tsx
  src/pages/Vote/DelegateModal/index.tsx
Labels: 0.8.0

#713 Update Venus Lens contract address on mainnet
  src/constants/contracts/addresses/main.json
Labels: hotfix

#715 Fix yearly earnings calculation
  src/pages/Dashboard/MyAccount/index.tsx
  src/utilities/calculateYearlyEarnings.spec.ts
  src/utilities/calculateYearlyEarnings.ts
  src/utilities/index.ts
Labels: hotfix
