Repository VenusProtocol/venus-protocol-interface, pull requests merged in 2022-07, with the labels that each got.

#709 [VEN-297] Remove redux
  package.json
  src/components/Layout/Header/index.stories.tsx
  src/components/Layout/PageContainer/index.stories.tsx
  src/components/Layout/Sidebar/index.stories.tsx
  src/core/index.ts
  src/core/modules/account/actions.ts
  src/core/modules/account/connectAccount.ts
  src/core/modules/account/index.ts
  src/core/modules/account/reducer.ts
  src/core/modules/account/saga.ts
  src/core/modules/auth/actions.ts
  src/core/modules/auth/connectAuth.ts
  src/core/modules/auth/index.ts
  src/core/modules/auth/reducer.ts
  src/core/modules/auth/saga.ts
  src/core/modules/index.ts
  src/core/modules/initialState.ts
  src/core/modules/reset/index.ts
  src/core/modules/reset/reducer.ts
  src/core/modules/utils/createPromiseAction.ts
  src/core/modules/utils/index.ts
  src/core/store/index.ts
  src/core/store/reducers.ts
  src/core/store/sagas.ts
  src/core/store/store.ts
  src/pages/App.tsx
  src/pages/ConvertVrt/index.stories.tsx
  src/pages/Dashboard/index.stories.tsx
  src/pages/Market/Header/index.stories.tsx
  src/pages/Market/MarketTable/index.stories.tsx
  src/pages/MarketDetails/Card/index.stories.tsx
  src/pages/MarketDetails/MarketInfo/index.stories.tsx
  src/pages/MarketDetails/index.stories.tsx
  src/pages/Vault/index.stories.tsx
  src/pages/VoterLeaderboard/index.stories.tsx
  src/pages/Xvs/index.stories.tsx
  src/stories/decorators.tsx
  src/utilities/localStorage.ts
  yarn.lock
Labels: 1.0.0

#717 [VEN-298] No collateralized supplied tokens warning
  src/__mocks__/models/asset.ts
  src/pages/Dashboard/Modals/BorrowRepay/Borrow/index.spec.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Borrow/index.tsx
  src/translation/translations/en.json
Labels: 0.9.0

#710 [VEN-320] Remove comma number
  package.json
  src/components/ProgressBar/index.tsx
  src/pages/Dashboard/Modals/SupplyWithdraw/SupplyWithdrawForm.tsx
  src/translation/translations/en.json
  src/utilities/commaFormat.ts
  src/utilities/format.ts
  src/utilities/formatCommaThousandsPeriodDecimal.ts
  src/utilities/index.ts
  yarn.lock
Labels: 1.0.0

#727 [VEN-377] Fix issues on Proposal Details page
  src/clients/api/index.ts
  src/clients/api/mutations/castVote/index.ts
  src/clients/api/mutations/vote/castVote.spec.ts
  src/clients/api/mutations/vote/castVote.ts
  src/clients/api/mutations/vote/castVoteWithReason.spec.ts
  src/clients/api/mutations/vote/castVoteWithReason.ts
  src/clients/api/mutations/vote/useCastVote.ts
  src/clients/api/mutations/vote/useCastVoteWithReason.ts
  src/clients/api/queries/getVoteReceipt/index.ts
  src/components/AuthModal/AccountDetails/index.tsx
  src/components/AuthModal/AccountDetails/styles.ts
  src/components/BscLink/index.tsx
  src/components/BscLink/styles.ts
  src/components/Countdown/index.tsx
  src/components/EllipseAddress/index.stories.tsx
  src/components/EllipseAddress/index.tsx
  src/components/EllipseAddress/styles.ts
  src/components/EllipseAddress/types.ts
  src/components/EllipseText/index.tsx
  src/components/EllipseText/styles.ts
  src/components/Layout/Header/Title/index.tsx
  src/components/Layout/Header/Title/styles.ts
  src/components/Layout/constants.tsx
  src/components/Layout/types.ts
  src/components/ProgressBar/LabeledProgressBar/index.tsx
  src/components/index.ts
  src/hooks/useVote.ts
  src/pages/History/HistoryTable/index.tsx
  src/pages/History/HistoryTable/styles.ts
  src/pages/Proposal/Description/index.tsx
  src/pages/Proposal/Description/styles.ts
  src/pages/Proposal/ProposalSummary/Stepper/index.tsx
  src/pages/Proposal/ProposalSummary/index.tsx
  src/pages/Proposal/ProposalSummary/styles.ts
  src/pages/Proposal/VoteModal/index.tsx
  src/pages/Proposal/VoteSummary/index.tsx
  src/pages/Proposal/VoteSummary/styles.ts
  src/pages/Proposal/index.spec.tsx
  src/pages/Proposal/index.tsx
  src/pages/Proposal/styles.ts
  src/pages/Vote/Governance/index.tsx
  src/pages/Vote/GovernanceProposal/index.tsx
  src/pages/Vote/GovernanceProposal/styles.ts
  src/pages/VoterLeaderboard/LeaderboardTable/index.tsx
  src/pages/VoterLeaderboard/LeaderboardTable/styles.ts
  src/pages/Xvs/Header/index.tsx
  src/pages/Xvs/styles.ts
  src/translation/translations/en.json
  src/utilities/truncateAddress.ts
Labels: 0.8.0

#729 [VEN-372] Do not round percentages
  src/utilities/calculatePercentage.ts
Labels: 0.9.0

#732 [VEN-298] Remove MarketContext
  src/context/MarketContext.tsx
  src/hooks/useMarkets.ts
  src/hooks/useMarketsUser.ts
  src/pages/App.tsx
  src/stories/decorators.tsx
Labels: 1.0.0

#728 Add vote tests
  src/__mocks__/models/address.ts
  src/components/ProposalCard/index.tsx
  src/pages/Vote/DelegateModal/index.stories.tsx
  src/pages/Vote/DelegateModal/index.tsx
  src/pages/Vote/GovernanceProposal/index.tsx
  src/pages/Vote/VotingWallet/index.tsx
  src/pages/Vote/index.spec.tsx
  src/pages/Vote/testIds.ts
  src/translation/translations/en.json
Labels: 0.8.0

#744 Refine proposal requests
  src/clients/api/__mocks__/index.ts
  src/clients/api/index.ts
  src/pages/Proposal/ProposalSummary/index.tsx
  src/pages/Proposal/VoteModal/index.tsx
  src/pages/Proposal/index.tsx
  src/pages/Vote/Governance/index.tsx
  src/pages/Vote/index.spec.tsx
Labels: 0.8.0

#741 Bump package version to 0.8.0
  package.json
Labels: 0.8.0

#743 Conditionally hide withdraw button of non-vesting VRT vault
  src/pages/Vault/VaultItem/index.spec.tsx
  src/pages/Vault/VaultItem/index.tsx
Labels: 1.0.0

#738 [VEN-393] Use 8 decimals to display token values + improve responsiveness of LabeledInlineContent
  src/components/LabeledInlineContent/index.tsx
  src/components/LabeledInlineContent/styles.ts
  src/components/SuccessfulTransactionModal/styles.ts
  src/pages/Dashboard/Modals/BorrowRepay/AccountData/index.tsx
  src/pages/Dashboard/Modals/SupplyWithdraw/SupplyWithdrawForm.tsx
  src/pages/Dashboard/Modals/SupplyWithdraw/index.spec.tsx
  src/pages/Dashboard/Modals/styles.ts
  src/pages/MarketDetails/__snapshots__/index.spec.tsx.snap
  src/pages/Proposal/VoteSummary/index.tsx
  src/pages/Proposal/VoteSummary/styles.ts
  src/translation/translations/en.json
  src/utilities/formatTokensToReadableValue.spec.ts
  src/utilities/formatTokensToReadableValue.ts
Labels: 1.0.0

#748 [VEN-382] Format action signature on frontend
  src/__mocks__/api/proposals.json
  src/clients/api/queries/getProposals/__snapshots__/getProposal.spec.ts.snap
  src/clients/api/queries/getProposals/__snapshots__/index.spec.ts.snap
  src/components/ReadableActionSignature/formatSignature.ts
  src/components/ReadableActionSignature/getContractName.ts
  src/components/ReadableActionSignature/index.tsx
  src/components/ReadableActionSignature/styles.ts
  src/components/index.ts
  src/pages/Proposal/Description/index.tsx
  src/pages/Proposal/index.spec.tsx
  src/pages/Vote/CreateProposalModal/ActionAccordion/CallDataFields.tsx
  src/pages/Vote/CreateProposalModal/ActionAccordion/index.tsx
  src/pages/Vote/CreateProposalModal/ProposalPreview/index.tsx
  src/pages/Vote/CreateProposalModal/formatProposalPayload.ts
  src/pages/Vote/CreateProposalModal/index.spec.tsx
  src/pages/Vote/CreateProposalModal/index.tsx
  src/pages/Vote/CreateProposalModal/proposalSchema.ts
  src/types/index.ts
Labels: 1.0.0

#749 [VEN-391] Display time until proposal can be executed
  src/__mocks__/contracts/governanceBravoDelegate.ts
  src/clients/api/__mocks__/index.ts
  src/clients/api/index.ts
  src/clients/api/queries/getProposalEta/__snapshots__/index.spec.ts.snap
  src/clients/api/queries/getProposalEta/index.spec.ts
  src/clients/api/queries/getProposalEta/index.ts
  src/clients/api/queries/getProposalEta/useGetProposalEta.ts
  src/constants/functionKey.ts
  src/pages/Proposal/ProposalSummary/index.tsx
  src/translation/translations/en.json
Labels: 1.0.0

#757 Correct reversed abstain and against
  src/pages/Vote/CreateProposalModal/formatProposalPayload.ts
Labels: bug

#756 [VEN-324] Separate constants from config
  .env.template
  .github/workflows/ci.yaml
  src/clients/api/queries/useGetTreasuryTotals.ts
  src/clients/web3/connectors.ts
  src/clients/web3/getWeb3NoAccount.ts
  src/clients/web3/useAuth/index.ts
  src/clients/web3/useAuth/setUpNetwork.ts
  src/clients/web3/useEagerConnect.ts
  src/components/AuthModal/WalletList/index.tsx
  src/components/AuthModal/constants.ts
  src/components/Layout/Footer/constants.ts
  src/components/Layout/Footer/index.tsx
  src/components/ReadableActionSignature/getContractName.ts
  src/config/index.ts
  src/constants/bsc.ts
  src/constants/endpoints.ts
  src/constants/localStorageKeys.ts
  src/constants/safeBorrowLimitPercentage.ts
  src/constants/tokens.ts
  src/pages/Dashboard/Modals/BorrowRepay/AccountData/index.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Borrow/index.spec.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Borrow/index.tsx
  src/pages/Dashboard/Modals/SupplyWithdraw/SupplyWithdrawForm.tsx
  src/pages/Dashboard/MyAccount/index.tsx
  src/pages/MarketDetails/useGetMarketData.ts
  src/types/index.ts
  src/utilities/generateBscScanUrl.ts
  src/utilities/getContractAddress.ts
  src/utilities/restService.ts
Labels: 1.0.0

#760 [VEN-390] Update auth modal UI to match design updates
  src/assets/img/v2/wallets/coinbaseWalletLogo.svg
  src/components/AuthModal/WalletList/index.tsx
  src/components/AuthModal/WalletList/styles.ts
  src/components/ReadableActionSignature/styles.ts
  src/pages/Vote/CreateProposalModal/ProposalPreview/styles.ts
  src/translation/translations/en.json
Labels: 1.0.0

#758 [VEN-390] Decouple test IDs
  src/components/Layout/ClaimXvsRewardButton/index.spec.tsx
  src/components/Layout/ClaimXvsRewardButton/index.tsx
  src/components/Layout/testIds.ts
  src/components/Spinner/index.tsx
  src/components/Spinner/testIds.ts
  src/constants/testIds.ts
  src/pages/ConvertVrt/Convert/index.spec.tsx
  src/pages/ConvertVrt/Convert/index.tsx
  src/pages/ConvertVrt/Convert/testIds.ts
  src/pages/Dashboard/Modals/BorrowRepay/Borrow/index.spec.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Borrow/index.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Borrow/testIds.ts
  src/pages/Dashboard/Modals/BorrowRepay/Repay/index.spec.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Repay/index.tsx
  src/pages/Dashboard/Modals/BorrowRepay/Repay/testIds.ts
  src/pages/History/index.spec.tsx
  src/pages/MarketDetails/index.spec.tsx
  src/pages/MarketDetails/index.tsx
  src/pages/MarketDetails/testIds.ts
  src/pages/Proposal/ProposalSummary/index.tsx
  src/pages/Proposal/ProposalSummary/testIds.ts
  src/pages/Proposal/VoteModal/index.tsx
  src/pages/Proposal/VoteModal/testIds.ts
  src/pages/Proposal/index.spec.tsx
  src/pages/Proposal/testIds.ts
  src/pages/Vault/TransactionForm/index.spec.tsx
  src/pages/Vault/TransactionForm/index.tsx
  src/pages/Vault/TransactionForm/testIds.ts
  src/pages/Vault/VaultItem/index.spec.tsx
  src/pages/Vault/VaultItem/index.tsx
  src/pages/Vault/VaultItem/testIds.ts
  src/pages/Vault/index.spec.tsx
  src/pages/Vault/modals/ActionModal/index.spec.tsx
  src/pages/Vault/modals/StakeModal/index.spec.tsx
  src/pages/Vault/modals/WithdrawFromVaiVaultModal/index.spec.tsx
  src/pages/Vault/modals/WithdrawFromVestingVaultModal/RequestWithdrawal/index.spec.tsx
  src/pages/Vault/modals/WithdrawFromVestingVaultModal/Withdraw/index.spec.tsx
  src/pages/Vault/modals/WithdrawFromVestingVaultModal/Withdraw/index.tsx
  src/pages/Vault/modals/WithdrawFromVestingVaultModal/Withdraw/testIds.ts
  src/pages/Vault/modals/WithdrawFromVestingVaultModal/WithdrawalRequestList/index.spec.tsx
  src/pages/Vault/modals/WithdrawFromVestingVaultModal/WithdrawalRequestList/index.tsx
  src/pages/Vault/modals/WithdrawFromVestingVaultModal/WithdrawalRequestList/testIds.ts
  src/pages/Vote/GovernanceProposal/index.tsx
  src/pages/Vote/GovernanceProposal/testIds.ts
  src/pages/Vote/VotingWallet/index.tsx
  src/pages/Vote/VotingWallet/testIds.ts
  src/pages/Vote/index.spec.tsx
  src/pages/Vote/testIds.ts
Labels: 1.0.0

#763 Update countdown indicating time until proposal is executable
  src/pages/Proposal/ProposalSummary/index.tsx
  src/pages/Proposal/ProposalSummary/styles.ts
  src/translation/translations/en.json
Labels: 1.0.0

#771 Delete unused images + remove v2 directory
  src/assets/img/arrow-right.png
  src/assets/img/close.png
  src/assets/img/dash.png
  src/assets/img/ethereum.png
  src/assets/img/fee.png
  src/assets/img/green-check.png
  src/assets/img/grey-check.png
  src/assets/img/logo.png
  src/assets/img/logo.svg
  src/assets/img/mark.svg
  src/assets/img/prdt.png
  src/assets/img/venus.svg
  src/assets/img/venusActive.svg
  src/assets/img/venusLogoPure.svg
  src/assets/img/venusLogoWithText.svg
  src/assets/img/wallets/binanceChainWalletLogo.svg
  src/assets/img/wallets/bitKeepLogo.svg
  src/assets/img/wallets/braveWalletLogo.svg
  src/assets/img/wallets/coinbaseWalletLogo.svg
  src/assets/img/wallets/infinityWalletLogo.svg
  src/assets/img/wallets/ledgerLogo.svg
  src/assets/img/wallets/metaMaskLogo.svg
  src/assets/img/wallets/operaWalletLogo.svg
  src/assets/img/wallets/safePalLogo.svg
  src/assets/img/wallets/trustWalletLogo.svg
  src/assets/img/wallets/walletConnectLogo.svg
  src/assets/img/withdraw-history.png
  src/assets/img/xvs.svg
  src/components/AuthModal/constants.ts
  src/components/Layout/Sidebar/index.tsx
  src/components/Select/styles.ts
  src/pages/Dashboard/Markets/SupplyMarket/CollateralConfirmModal/index.tsx
Labels: 1.1.0
