Repository VenusProtocol/venus-protocol-interface, pull requests merged in 2023-04, with the labels that each got.

#1013 Revert vesting vault changes
  src/clients/api/__mocks__/index.ts
  src/clients/api/index.ts
  src/clients/api/queries/getXvsVaultPendingWithdrawalsFromBeforeUpgrade/__snapshots__/index.spec.ts.snap
  src/clients/api/queries/getXvsVaultPendingWithdrawalsFromBeforeUpgrade/index.spec.ts
  src/clients/api/queries/getXvsVaultPendingWithdrawalsFromBeforeUpgrade/index.ts
  src/clients/api/queries/getXvsVaultPendingWithdrawalsFromBeforeUpgrade/types.ts
  src/clients/api/queries/getXvsVaultPendingWithdrawalsFromBeforeUpgrade/useGetXvsVaultPendingWithdrawalsFromBeforeUpgrade.ts
  src/clients/api/queries/useGetVaults/__snapshots__/index.spec.tsx.snap
  src/clients/api/queries/useGetVaults/index.spec.tsx
  src/clients/api/queries/useGetVaults/useGetVestingVaults/index.ts
  src/clients/api/queries/useGetVaults/useGetVestingVaults/useGetXvsVaultPools.ts
  src/constants/contracts/abis/xvsVault.json
  src/constants/functionKey.ts
  src/pages/Vault/VaultItem/index.tsx
  src/pages/Vault/modals/WithdrawFromVestingVaultModal/index.spec.tsx
  src/pages/Vault/modals/WithdrawFromVestingVaultModal/index.tsx
  src/translation/translations/en.json
  src/types/index.ts
Labels: hotfix

#1008 [VEN-870] Updated high risk borrow warning
  src/hooks/useBorrowRepayModal/Modal/Borrow/BorrowSection/index.tsx
  src/hooks/useBorrowRepayModal/Modal/Borrow/Notice.tsx
  src/hooks/useBorrowRepayModal/Modal/Borrow/index.spec.tsx
  src/hooks/useBorrowRepayModal/Modal/Borrow/index.tsx
  src/hooks/useBorrowRepayModal/Modal/Borrow/testIds.ts
  src/hooks/useBorrowRepayModal/Modal/styles.ts
  src/translation/translations/en.json
Labels: 2.0.0

#1015 [VEN-1264] Update testnet tokens used in the swap
  src/__mocks__/contracts/multicall.ts
  src/__mocks__/models/tokenCombinations.ts
  src/clients/api/queries/getPancakeSwapPairs/__tests__/__snapshots__/generateTokenCombinationIds.spec.ts.snap
  src/clients/api/queries/getPancakeSwapPairs/__tests__/__snapshots__/index.spec.ts.snap
  src/clients/api/queries/getPancakeSwapPairs/formatToPairs.ts
  src/clients/api/queries/getTokenBalances/__snapshots__/index.spec.ts.snap
  src/constants/tokens/common/testnet.ts
  src/constants/tokens/pancakeSwap/testnet.ts
  src/hooks/useGetSwapInfo/__tests__/__snapshots__/formatToSwap.spec.ts.snap
  src/hooks/useGetSwapInfo/__tests__/__snapshots__/index.spec.tsx.snap
  src/hooks/useGetSwapInfo/__tests__/__snapshots__/useGetTokenCombinations.spec.tsx.snap
  src/hooks/useGetSwapInfo/__tests__/index.spec.tsx
  src/hooks/useGetSwapInfo/useGetTokenCombinations.ts
  src/pages/Swap/__tests__/__snapshots__/index.spec.tsx.snap
  src/pages/Swap/__tests__/index.spec.tsx
  src/pages/Swap/index.tsx
Labels: 2.0.0

#1019 Fix displayed hash on Proposal page
  src/pages/Governance/ProposalList/GovernanceProposal/index.tsx
  src/pages/Proposal/ProposalSummary/index.tsx
  src/translation/translations/en.json
Labels: 2.0.0

#1020 Fix background color of Notice component
  src/components/Notice/styles.ts
Labels: 2.0.0

#1026 [VEN-1234] Swap improvements
  .eslintignore
  .eslintrc.js
  .gitignore
  package.json
  scripts/generatePancakeSwapTokens.mts
  scripts/runGenerateSubgraphTypes.sh
  src/__mocks__/models/tokenBalances.ts
  src/__mocks__/models/tokenCombinations.ts
  src/clients/api/mutations/swapTokens/index.spec.ts
  src/clients/api/queries/getTokenBalances/index.spec.ts
  src/components/SelectTokenTextField/TokenList/index.tsx
  src/components/SelectTokenTextField/TokenList/styles.ts
  src/components/SelectTokenTextField/index.stories.tsx
  src/constants/tokens/index.ts
  src/constants/tokens/pancakeSwap/mainnet.ts
  src/constants/tokens/swap/mainnet.ts
  src/constants/tokens/swap/testnet.ts
  src/hooks/useBorrowRepayModal/Modal/RepayForm/__tests__/indexIntegratedSwap.spec.tsx
  src/hooks/useGetSwapInfo/__tests__/formatToSwap.spec.ts
  src/hooks/useGetSwapInfo/__tests__/index.spec.tsx
  src/hooks/useGetSwapInfo/__tests__/useGetTokenCombinations.spec.tsx
  src/hooks/useGetSwapInfo/__tests__/wrapToken.spec.ts
  src/hooks/useGetSwapInfo/useGetTokenCombinations.ts
  src/hooks/useGetSwapInfo/wrapToken.ts
  src/hooks/useGetSwapTokenUserBalances.ts
  src/pages/Swap/__tests__/fakeData.ts
  src/pages/Swap/__tests__/index.spec.tsx
  src/pages/Swap/index.tsx
  src/pages/Swap/useFormValidation.ts
  tsconfig.json
  yarn.lock
Labels: 2.1.0

#1030 [VEN-1357] Refactor Borrow form to follow new file structure
  src/hooks/useBorrowRepayModal/Modal/Borrow/BorrowSection/index.tsx
  src/hooks/useBorrowRepayModal/Modal/Borrow/index.tsx
  src/hooks/useBorrowRepayModal/Modal/BorrowForm/Notice.tsx
  src/hooks/useBorrowRepayModal/Modal/BorrowForm/SubmitSection/index.tsx
  src/hooks/useBorrowRepayModal/Modal/BorrowForm/SubmitSection/styles.ts
  src/hooks/useBorrowRepayModal/Modal/BorrowForm/__tests__/fakeData.ts
  src/hooks/useBorrowRepayModal/Modal/BorrowForm/__tests__/index.spec.tsx
  src/hooks/useBorrowRepayModal/Modal/BorrowForm/index.stories.tsx
  src/hooks/useBorrowRepayModal/Modal/BorrowForm/index.tsx
  src/hooks/useBorrowRepayModal/Modal/BorrowForm/testIds.ts
  src/hooks/useBorrowRepayModal/Modal/BorrowForm/useForm/index.tsx
  src/hooks/useBorrowRepayModal/Modal/BorrowForm/useForm/types.ts
  src/hooks/useBorrowRepayModal/Modal/BorrowForm/useForm/useFormValidation.ts
  src/hooks/useBorrowRepayModal/Modal/index.tsx
  src/translation/translations/en.json
Labels: 2.1.0

#1032 Remove the concept of risk rating
  src/__mocks__/models/pools.ts
  src/clients/api/queries/getIsolatedPools/__tests__/__snapshots__/index.spec.ts.snap
  src/clients/api/queries/getIsolatedPools/__tests__/fakeData.ts
  src/clients/api/queries/getIsolatedPools/formatOutput/index.ts
  src/clients/api/queries/useGetMainPool/__snapshots__/index.spec.tsx.snap
  src/clients/api/queries/useGetMainPool/index.tsx
  src/clients/api/queries/useGetPool/__snapshots__/index.spec.tsx.snap
  src/clients/api/queries/useGetPools/__snapshots__/index.spec.tsx.snap
  src/components/RiskLevel/index.stories.tsx
  src/components/RiskLevel/index.tsx
  src/components/RiskLevel/styles.ts
  src/components/index.ts
  src/constants/localStorageKeys.ts
  src/constants/poolRiskRatingMapping.ts
  src/containers/MarketTable/types.ts
  src/containers/MarketTable/useGenerateColumns.tsx
  src/pages/Account/PoolBreakdown/__snapshots__/index.spec.tsx.snap
  src/pages/Account/PoolBreakdown/index.tsx
  src/pages/Dashboard/HigherRiskTokensNotice/index.tsx
  src/pages/Dashboard/HigherRiskTokensNotice/styles.ts
  src/pages/Dashboard/index.stories.tsx
  src/pages/Dashboard/index.tsx
  src/pages/Dashboard/styles.ts
  src/pages/Dashboard/useFormatPools.ts
  src/pages/Pools/PoolTable/index.tsx
  src/translation/translations/en.json
  src/types/index.ts
  src/utilities/comparePoolRiskRatings.ts
  src/utilities/index.ts
Labels: 2.0.0

#1018 [VEN-1272][VEN-1270] Finalize Swap and Repay flow
  src/__mocks__/models/swaps.ts
  src/clients/api/__mocks__/index.ts
  src/clients/api/index.ts
  src/clients/api/mutations/swapTokens/index.spec.ts
  src/clients/api/mutations/swapTokens/index.ts
  src/clients/api/mutations/swapTokensAndRepay/index.spec.ts
  src/clients/api/mutations/swapTokensAndRepay/index.ts
  src/clients/api/mutations/swapTokensAndRepay/useSwapTokensAndRepay.ts
  src/clients/contracts/getters.ts
  src/clients/contracts/hooks.ts
  src/components/EnableToken/index.spec.tsx
  src/components/EnableTokenSteps/index.spec.tsx
  src/components/EnableTokenSteps/index.tsx
  src/components/EnableTokenSteps/styles.ts
  src/components/index.ts
  src/constants/contracts/abis/swapRouter.json
  src/constants/contracts/addresses/main.json
  src/constants/functionKey.ts
  src/constants/transactionTimeout.ts
  src/containers/AssetAccessor/index.spec.tsx
  src/hooks/useBorrowRepayModal/Modal/RepayForm/SubmitSection/index.tsx
  src/hooks/useBorrowRepayModal/Modal/RepayForm/SubmitSection/styles.ts
  src/hooks/useBorrowRepayModal/Modal/RepayForm/SwapDetails/index.tsx
  src/hooks/useBorrowRepayModal/Modal/RepayForm/__tests__/__snapshots__/indexIntegratedSwap.spec.tsx.snap
  src/hooks/useBorrowRepayModal/Modal/RepayForm/__tests__/index.spec.tsx
  src/hooks/useBorrowRepayModal/Modal/RepayForm/__tests__/indexIntegratedSwap.spec.tsx
  src/hooks/useBorrowRepayModal/Modal/RepayForm/index.stories.tsx
  src/hooks/useBorrowRepayModal/Modal/RepayForm/index.tsx
  src/hooks/useBorrowRepayModal/Modal/RepayForm/testIds.ts
  src/hooks/useBorrowRepayModal/Modal/RepayForm/useForm/index.tsx
  src/hooks/useBorrowRepayModal/Modal/RepayForm/useForm/types.ts
  src/hooks/useBorrowRepayModal/Modal/RepayForm/useForm/useFormValidation.ts
  src/hooks/useBorrowRepayModal/Modal/RepayForm/useForm/validationSchema.ts
  src/hooks/useGetSwapInfo/index.ts
  src/hooks/useGetSwapInfo/types.ts
  src/hooks/useSupplyWithdrawModal/Modal/Supply/index.spec.tsx
  src/hooks/useSupplyWithdrawModal/Modal/Withdraw/index.spec.tsx
  src/hooks/useSupplyWithdrawModal/Modal/index.spec.tsx
  src/initializeLibraries/yup/yup-extensions.d.ts
  src/pages/ConvertVrt/Convert/index.spec.tsx
  src/pages/Swap/SubmitSection/index.tsx
  src/pages/Swap/__tests__/fakeData.ts
  src/pages/Swap/__tests__/index.spec.tsx
  src/pages/Swap/__tests__/testUtils.ts
  src/pages/Swap/index.tsx
  src/pages/Swap/styles.ts
  src/pages/Swap/useFormValidation.ts
  src/pages/Vai/MintVai/index.spec.tsx
  src/pages/Vai/RepayVai/index.spec.tsx
  src/pages/Vai/index.spec.tsx
  src/pages/Vault/modals/ActionModal/index.spec.tsx
  src/pages/Vault/modals/StakeModal/index.spec.tsx
  src/pages/Vault/modals/WithdrawFromVaiVaultModal/index.spec.tsx
  src/pages/Vault/modals/WithdrawFromVestingVaultModal/RequestWithdrawal/index.spec.tsx
  src/setupTests.ts
  src/translation/translations/en.json
  src/types/index.ts
  src/utilities/generateTransactionDeadline.ts
  src/utilities/index.ts
Labels: 2.1.0
