Repository VenusProtocol/venus-protocol-interface, pull requests merged in 2023-03, with the labels that each got.

#966 [VEN-932] Add claimRewards mutation function
  package.json
  src/__mocks__/contracts/multicall.ts
  src/__mocks__/contracts/xvsVault.ts
  src/clients/api/__mocks__/index.ts
  src/clients/api/index.ts
  src/clients/api/mutations/claimRewards/__snapshots__/index.spec.ts.snap
  src/clients/api/mutations/claimRewards/index.spec.ts
  src/clients/api/mutations/claimRewards/index.ts
  src/clients/api/mutations/claimRewards/types.ts
  src/clients/api/mutations/claimRewards/useClaimRewards.ts
  src/clients/api/mutations/claimVaiVaultReward/index.spec.ts
  src/clients/api/mutations/claimVaiVaultReward/index.ts
  src/clients/api/mutations/claimVaiVaultReward/useClaimVaiVaultReward.ts
  src/clients/api/mutations/claimVrtVaultReward/index.spec.ts
  src/clients/api/mutations/claimVrtVaultReward/index.ts
  src/clients/api/mutations/claimVrtVaultReward/useClaimVrtVaultReward.ts
  src/clients/api/mutations/claimXvsReward/index.spec.ts
  src/clients/api/mutations/claimXvsReward/index.ts
  src/clients/api/mutations/claimXvsReward/useClaimXvsReward.ts
  src/clients/api/mutations/claimXvsVaultReward/index.spec.ts
  src/clients/api/mutations/claimXvsVaultReward/index.ts
  src/clients/api/mutations/claimXvsVaultReward/useClaimXvsVaultReward.ts
  src/clients/api/queries/getPendingRewards/__tests__/__snapshots__/index.spec.ts.snap
  src/clients/api/queries/getPendingRewards/formatOutput/formatToPoolPendingRewardGroup/formatToPoolPendingRewards.ts
  src/clients/api/queries/getPendingRewards/formatOutput/index.ts
  src/clients/api/queries/getPendingRewards/index.ts
  src/clients/api/queries/getPendingRewards/types.ts
  src/clients/contracts/getters.ts
  src/clients/contracts/hooks.ts
  src/components/Layout/ClaimRewardButton/__tests__/__snapshots__/index.spec.tsx.snap
  src/components/Layout/ClaimRewardButton/__tests__/fakeData.ts
  src/components/Layout/ClaimRewardButton/index.tsx
  src/components/Layout/ClaimRewardButton/useGetGroups.ts
  src/constants/contracts/abis/multicall.json
  src/constants/contracts/abis/vaiVault.json
  src/constants/contracts/abis/vrtVault.json
  src/constants/contracts/abis/xvsVault.json
  src/constants/contracts/addresses/main.json
  src/constants/functionKey.ts
  yarn.lock
Labels: 2.0.0

#981 Limit percentages to a maximum value
  src/clients/api/queries/getIsolatedPools/formatToPool.ts
  src/utilities/formatPercentage.ts
Labels: 2.0.0

#984 Remove limit parameter from getMarketHistory function
  src/clients/api/queries/getMarketHistory/index.spec.ts
  src/clients/api/queries/getMarketHistory/index.ts
Labels: 2.0.0

#994 Update OKX logo
  src/assets/img/wallets/okxLogo.svg
Labels: 2.0.0

#992 [VEN-1221] Release isolated lending under feature flag
  .env.template
  package.json
  src/App/Switch/index.tsx
  src/clients/api/queries/getPendingRewards/__tests__/__snapshots__/index.spec.ts.snap
  src/clients/api/queries/getPendingRewards/__tests__/index.spec.ts
  src/clients/api/queries/getPendingRewards/formatOutput/formatToIsolatedPoolPendingRewardGroup.ts
  src/clients/api/queries/getPendingRewards/formatOutput/formatToMainPoolPendingRewardGroup.ts
  src/clients/api/queries/getPendingRewards/index.ts
  src/clients/api/queries/useGetPools/index.tsx
  src/components/Layout/ClaimRewardButton/useGetGroups.ts
  src/components/Layout/Header/Breadcrumbs/index.tsx
  src/components/Layout/Sidebar/useGetMenuItems.tsx
  src/config/index.ts
  src/constants/disabledTokens.ts
  src/constants/routing.ts
  src/containers/MarketTable/types.ts
  src/containers/MarketTable/useGenerateColumns.tsx
  src/hooks/useBorrowRepayModal/Modal/index.spec.tsx
  src/hooks/useSupplyWithdrawModal/Modal/Supply/index.spec.tsx
  src/pages/Account/PoolBreakdown/index.tsx
  src/pages/Account/index.tsx
  src/pages/Dashboard/index.spec.tsx
  src/pages/Dashboard/index.tsx
  src/pages/Dashboard/styles.ts
  src/pages/Pool/index.tsx
  src/pages/Xvs/index.tsx
  src/translation/translations/en.json
  src/utilities/index.ts
  src/utilities/isTokenEnabled.ts
Labels: 1.6.0

#999 [VEN-1235] Unify link design
  src/assets/styles/Global.scss
  src/assets/styles/normalize.scss
  src/components/AuthModal/WalletList/index.tsx
  src/components/AuthModal/WalletList/styles.ts
  src/components/BscLink/styles.ts
  src/components/Layout/Header/Breadcrumbs/index.tsx
  src/components/Layout/Header/Breadcrumbs/styles.ts
  src/components/Layout/Sidebar/styles.ts
  src/components/Markdown/Editor/styles-overrides.scss
  src/components/Notice/styles.ts
  src/components/ProposalCard/index.tsx
  src/components/ProposalCard/styles.ts
  src/components/Table/TableCards.tsx
  src/components/Table/index.tsx
  src/components/Table/styles.ts
  src/pages/Governance/VotingWallet/DelegateModal/styles.ts
  src/pages/Governance/VotingWallet/styles.ts
Labels: 1.6.0

#1007 Reorder side menu items to put VAI before Convert VRT
  src/components/Layout/Sidebar/useGetMenuItems.tsx
Labels: 2.0.0

#1003 [VEN-864] Added XVS snapshot link to governance page
  src/components/Button/index.tsx
  src/components/Button/styles.tsx
  src/constants/xvsSnapshotUrl.ts
  src/pages/Governance/VotingWallet/index.tsx
  src/pages/Governance/VotingWallet/styles.ts
  src/translation/translations/en.json
Labels: 2.0.0

#1005 [VEN-1165] Fetch isolated pools directly from contracts
  package.json
  src/__mocks__/contracts/multicall.ts
  src/clients/api/queries/getIsolatedPools/__tests__/__snapshots__/index.spec.ts.snap
  src/clients/api/queries/getIsolatedPools/__tests__/fakeData.ts
  src/clients/api/queries/getIsolatedPools/__tests__/index.spec.ts
  src/clients/api/queries/getIsolatedPools/formatOutput/convertFactorFromSmartContract.ts
  src/clients/api/queries/getIsolatedPools/formatOutput/formatToDistributions.ts
  src/clients/api/queries/getIsolatedPools/formatOutput/index.ts
  src/clients/api/queries/getIsolatedPools/formatToPool.ts
  src/clients/api/queries/getIsolatedPools/index.ts
  src/clients/api/queries/getIsolatedPools/types.ts
  src/clients/api/queries/getIsolatedPools/useGetIsolatedPools.ts
  src/clients/api/queries/getPendingRewards/__tests__/__snapshots__/index.spec.ts.snap
  src/clients/api/queries/getPendingRewards/__tests__/index.spec.ts
  src/clients/api/queries/getPendingRewards/index.ts
  src/clients/api/queries/useGetMainPool/index.tsx
  src/clients/contracts/getters.ts
  src/clients/contracts/hooks.ts
  src/clients/subgraph/__mocks__/index.ts
  src/clients/subgraph/index.ts
  src/clients/subgraph/queries/getIsolatedPoolParticipantsCount/index.ts
  src/clients/subgraph/queries/getIsolatedPoolParticipantsCount/isolatedPoolParticipantsCount.graphql
  src/clients/subgraph/queries/getIsolatedPools/index.ts
  src/clients/subgraph/queries/getIsolatedPools/isolatedPools.graphql
  src/constants/contracts/abis/poolLens.json
  src/constants/contracts/addresses/main.json
  src/constants/tokens/common/testnet.ts
  src/constants/tokens/vBep/testnet.ts
  src/hooks/useBorrowRepayModal/Modal/Borrow/index.tsx
  src/hooks/useSupplyWithdrawModal/Modal/Supply/form.tsx
  src/hooks/useSupplyWithdrawModal/Modal/Supply/index.tsx
  src/hooks/useSupplyWithdrawModal/Modal/Withdraw/index.tsx
  src/types/index.ts
  src/utilities/addUserPropsToPool.ts
  src/utilities/areAddressesEqual.ts
  src/utilities/index.ts
  yarn.lock
Labels: 2.0.0

#1011 [VEN-1272] Refactor Repay form in preparation for integrated swap feature
  .env.template
  src/config/index.ts
  src/containers/AssetAccessor/index.spec.tsx
  src/containers/AssetAccessor/index.tsx
  src/hooks/useBorrowRepayModal/Modal/Repay/index.tsx
  src/hooks/useBorrowRepayModal/Modal/RepayForm/index.spec.tsx
  src/hooks/useBorrowRepayModal/Modal/RepayForm/index.stories.tsx
  src/hooks/useBorrowRepayModal/Modal/RepayForm/index.tsx
  src/hooks/useBorrowRepayModal/Modal/RepayForm/styles.ts
  src/hooks/useBorrowRepayModal/Modal/RepayForm/testIds.ts
  src/hooks/useBorrowRepayModal/Modal/RepayForm/useForm.ts
  src/hooks/useBorrowRepayModal/Modal/index.tsx
  src/hooks/useFormatTokensToReadableValue.ts
  src/utilities/formatTokensToReadableValue.ts
  src/utilities/index.ts
Labels: 2.10

#1010 [VEN-1066][VEN-1130] Add analytics and error logger
  .env.template
  .gitignore
  package.json
  src/App/index.tsx
  src/clients/api/queries/getIsolatedPools/formatOutput/formatToDistributions.ts
  src/clients/api/queries/getIsolatedPools/formatOutput/index.ts
  src/clients/api/queries/getIsolatedPools/index.ts
  src/clients/api/queryClient.ts
  src/config/index.ts
  src/constants/dAppHosts.ts
  src/context/Analytics/index.tsx
  src/context/ErrorLogger/index.tsx
  src/types/index.ts
  yarn.lock
Labels: 2.0.0
